### ISSUE TITLE
Invalid cross-device link

### ISSUE THREAD

**Issue by cmarkello** [DataBiosphere/toil#1400]
@cket 
Getting `OSError: [Errno 18] Invalid cross-device link` when running `./jenkins` in the `master` branch of `toil-vg` on an AWS instance which is using the single machine batch system. Not sure if this is a toil issue, but it appears as though whatever was merged to master last should not have passed the unit tests on jenkins. So it's either that or there's a difference between running `./jenkins` on a 4.2xlarge aws instance and running the unit tests on the official jenkins server.

Versions:
`toil (3.5.0a1.dev251)`
`toil-lib (1.1.0a1)` (custom toil-lib version from https://github.com/cmarkello/toil-lib)
`toil-vg (1.1.0a1)`

Forwarded from  https://github.com/BD2KGenomics/toil-vg/issues/84

Traceback:
```
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.job:Loading user function run_xg_indexing from module ModuleDescriptor(dirPath='/home/mesosbox/toil-vg/src', name='toil_vg.vg_index', fromVirtualEnv=False).
L/Y/jobRtcOBD    WARNING:toil.resource:Can't find resource for leader path '/home/mesosbox/toil-vg/src/toil_vg'
L/Y/jobRtcOBD    WARNING:toil.resource:Can't localize module ModuleDescriptor(dirPath='/home/mesosbox/toil-vg/src', name='toil_vg.vg_index', fromVirtualEnv=False)
L/Y/jobRtcOBD    INFO:realtime:Starting xg indexing...
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Cache miss on file with ID 'b/o/tmpZYsFhp.tmp'.
L/Y/jobRtcOBD    DEBUG:toil.fileStore:LOG-TO-MASTER: CACHE: Creating a harbinger file for (b/o/tmpZYsFhp.tmp). 
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:LOG-TO-MASTER: CACHE: Deleting the harbinger file for (b/o/tmpZYsFhp.tmp)
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Obtained lock on file /var/lib/toil/toil-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/cache-0e550c40-21b0-4b43-ba7a-dcecb0e0f0a1/.cacheLock
L/Y/jobRtcOBD    DEBUG:toil.fileStore:CACHE: Released lock
L/Y/jobRtcOBD    Traceback (most recent call last):
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/worker.py", line 331, in main
L/Y/jobRtcOBD        job._runner(jobWrapper=jobWrapper, jobStore=jobStore, fileStore=fileStore)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/job.py", line 1172, in _runner
L/Y/jobRtcOBD        returnValues = self._run(jobWrapper, fileStore)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/job.py", line 1120, in _run
L/Y/jobRtcOBD        return self.run(fileStore)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/job.py", line 1283, in run
L/Y/jobRtcOBD        rValue = userFunction(*((self,) + tuple(self._args)), **self._kwargs)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/src/toil_vg/vg_index.py", line 213, in run_xg_indexing
L/Y/jobRtcOBD        read_from_store(job, options, inputGraphFileID, graph_filename)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/src/toil_vg/vg_common.py", line 230, in read_from_store
L/Y/jobRtcOBD        return job.fileStore.readGlobalFile(id_or_key, path)
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/fileStore.py", line 380, in readGlobalFile
L/Y/jobRtcOBD        '/.'.join(os.path.split(cachedFileName)))
L/Y/jobRtcOBD      File "/home/mesosbox/toil-vg/.env/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 240, in readFile
L/Y/jobRtcOBD        os.link(jobStoreFilePath, localFilePath)
L/Y/jobRtcOBD    OSError: [Errno 18] Invalid cross-device link
L/Y/jobRtcOBD    Exiting the worker because of a failed jobWrapper on host ip-172-31-31-184
L/Y/jobRtcOBD    ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host ip-172-31-31-184
L/Y/jobRtcOBD    WARNING:toil.jobWrapper:Due to failure we are reducing the remaining retry count of job L/Y/jobRtcOBD to 0
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-123)
┆Issue Number: TOIL-123

**Comment by jvivian** [comment]
What is the full command that produced this error?

**Comment by jvivian** [comment]
Nevermind, wrong ticket.

**Comment by cket** [comment]
I believe that there is an optimization in the file job store that just hard links files from the job store to the local dir instead of copying, and that is what is causing this error. An easy fix is to copy if linking fails. 

@cmarkello there are configuration differences between running ./jenkins and the actual Jenkins instances - if you want to replicate Jenkins more closely you can use CGCloud to spin up instances with Jenkins Slave roles.

**Comment by glennhickey** [comment]
@cket I was just running into this too.  It's because on the toil cluster created by cgcloud, you get
TOIL_WORKDIR="/var/lib/toil"

For some reason, this gets its own mount point.  as seen in /proc/mounts
/dev/xvda1 /var/lib/toil ext4 rw,relatime,data=ordered 0 0

Now even though this is the same *device* as, say, /tmp (which is also on /dev/xvda1), because it's a different mount point you get the crosslink error.   But the check within toil using os.stat().st_dev doesn't catch this (https://github.com/BD2KGenomics/toil/blob/master/src/toil/jobStores/fileJobStore.py#L236)

FWIW, you can quickly reproduce on the command line.  On instance set up as described here: https://github.com/BD2KGenomics/toil-vg

cd
touch x
ln x /var/lib/toil/x
ln: failed to create hard link ‘/var/lib/toil/x’ => ‘x’: Invalid cross-device link

But both devices the same:

df .
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1      10178756 6111572   3548480  64% /
mesosbox@ip-172-31-22-85:~$ df /var/lib/toil/
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1      10178756 6111572   3548480  64% /var/lib/toil

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
