### ISSUE TITLE
--maxCores being respected?

### ISSUE THREAD

**Issue by brainstorm** [DataBiosphere/toil#1796]
Hello Toil team,

While testing Toil with [bcbio_test_cwl](https://github.com/bcbio/test_bcbio_cwl) we found out that passing, i.e `--maxCores 1` to the commandline in [run_toil.sh](https://github.com/bcbio/test_bcbio_cwl/blob/master/run_toil.sh) does not seem to enforce that limit.

I guess that, i.e, on torque/PBS systems I could just pass `--maxCores N` to `#PBS -l ncpus=N` and be done with it, but I wonder if you had any refactoring plans on that regard?

It is definitely a critical feature we need in order to limit bcbio's use of cores and threads. We do it via ipyparallel and bcbio at the moment, but we would love to have this possibility in CWLToil too.

/cc @chapmanb @ohofmann

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-188)
┆Issue Number: TOIL-188

**Comment by DailyDreaming** [comment]
Can you provide 'bcbio_vm.py'?

**Comment by DailyDreaming** [comment]
Hi, I just attempted to reproduce the problem.  Are you passing "--maxCores 1" inside of the sh file like so:
"bcbio_vm.py cwlrun toil --no-container run_info-cwl-workflow --maxCores 1"?

I am testing on test_bcbio_cwl repo 1757c15 from 18 days ago since the repo seems to have been updated and no longer contains your original linked .sh file.
I am referencing this sh file: https://github.com/bcbio/test_bcbio_cwl/blob/b3697af38f6749b5c26c680e4b48f4d3cd0addaf/run_toil.sh

**Comment by brainstorm** [comment]
@DailyDreaming I hope that the quickstart @chapmanb put together helps you on testing this, let me know if your run into other issues.

**Comment by ejacox** [comment]
Copied from #1810 "For --maxCores, we need more of a global metric in Toil rather than task specific changes in the CWL support. We can already specify correctly how many cores/CPU a particular task uses but would like to be able to say something like: Run these 100 tasks each using 8 cores and 32Gb of memory, but only allocate up to 64 total cores at a time. Then Toil would run these in batches for 8 at a time, cycling through the 100. I believe this works cleanly on single machines and AWS but not sure about on
batch systems."

**Comment by DailyDreaming** [comment]
I believe this is fixed.  Pleas reopen if this is still an issue.
