### ISSUE TITLE
toil-cwl-runner --restart retains old memory requirement for some jobs, but updates for others

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2042]
I ran a failed run with the `--restart` parameter on our `lsf` system using `toil 3.8.0a1` and `cwltool 1.0.20170413194156`

It seems as if for one of the jobs, the new resourceRequirement that I specified was respected (`50 G`), while for another instance of the job, the old value was used (`4.0 M`)

(I'm comparing the two `cmo_fulcrum_group_reads_by_umi` jobs, which are both instances of the same cwl workflow)

```
luna.cbio.private 2018-02-02 16:45:27,608 MainThread INFO toil.leader: Issued job 'cmo_fulcrum_sort_bam' cmo_fulcrum_sort_bam l/7/jobDCL7HJ with job batch system ID: 0 and cores: 1, disk: 2.0 G, and memory: 50.0 G
luna.cbio.private 2018-02-02 16:45:32,633 MainThread INFO toil.leader: Issued job 'cmo_fulcrum_group_reads_by_umi' cmo_fulcrum_group_reads_by_umi F/9/jobblkFcr with job batch system ID: 1 and cores: 1, disk: 2.0 G, and memory: 50.0 G
luna.cbio.private 2018-02-02 17:19:12,688 MainThread INFO toil.leader: Job ended successfully: 'cmo_fulcrum_sort_bam' cmo_fulcrum_sort_bam l/7/jobDCL7HJ
luna.cbio.private 2018-02-02 17:19:17,751 MainThread INFO toil.leader: Issued job 'cmo_fulcrum_set_mate_information' cmo_fulcrum_set_mate_information p/K/job9FhzOo with job batch system ID: 2 and cores: 1, disk: 2.0 G, and memory: 4.0 M
luna.cbio.private 2018-02-02 17:44:44,474 MainThread INFO toil.leader: Job ended successfully: 'cmo_fulcrum_set_mate_information' cmo_fulcrum_set_mate_information p/K/job9FhzOo
luna.cbio.private 2018-02-02 17:44:49,541 MainThread INFO toil.leader: Issued job 'cmo_fulcrum_group_reads_by_umi' cmo_fulcrum_group_reads_by_umi m/c/jobllrrQA with job batch system ID: 3 and cores: 1, disk: 2.0 G, and memory: 4.0 M
```

Let me know if I can provide any additional information. Will try to dig up more details on this to make sure I'm not missing anything, or perhaps this might not exist in a newer version.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-225)
┆Issue Number: TOIL-225

**Comment by DailyDreaming** [comment]
It's difficult to know from an older version of Toil, as there have been some changes to how cwltoil handles requirements, especially since version 3.10.0 when there was a large push to update our support for CWL 1.0.1.

The easiest method is likely attempting this with a newer version of toil.  Any fix we make for this would be in a newer version anyway.

Otherwise, I suspect it might be how you're allocating resources in your cwl file.  My first thought is to check `outdirMin` in your `hints` section.

**Comment by ionox0** [comment]
Thank you @DailyDreaming I'm not using any `hints` but I'll be working on upgrading to a newer version in the near future. Will keep you posted

**Comment by cricketsloan** [comment]
➤ Adam Novak commented:

I suspect that what’s going on here is that already-created jobs in the jobStore had the old memory requirement that they were created with, while new jobs created during the new run might get the new requirement.

That’s expected behavior, unfortunately. The restart option can’t fix flawed jobs, only flawed code that the jobs will run when they actually execute. The \-\-defaultMemory option is one way to try and rescue a workflow with too-low memory requirements; when jobs fail, they have their memory requirements upped to whatever \-\-defaultMemory sets, for when they are next retried. If that doesn’t work for you, the best thing to do is to start the workflow over.
