### ISSUE TITLE
i3.4xlarge does not respect nodeTypes/maxNodes

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#2195]
When I run with `--nodeTypes i3.8xlarge,r3.8xlarge:0.70 --maxNodes 2,5`, my scripts seems to behave as expected:  My pre-emptable jobs get sent to r3.8xlarge spot requests, and at most 5 are made.  The non-pre-emptable job goes to an on-demand i3.8xlarge as I'd expect.  

But when I change i3.8xlarge to i3.4xlarge for the same script: `--nodeTypes i3.4xlarge,r3.8xlarge:0.70 --maxNodes 2,5` things change:  All my pre-emptable jobs get sent to on-demand i3.4xlarge nodes.  And Toil tries to initialize 5 of these, despite my limit of 2.  This is not at all what my command line is telling it (and currently causes my workflow to crash with the nodes still running because my account has a limit of 2).

All other related options (such as --preemptableCompensation) are defaults.  Using Version: quay.io/ucsc_cgl/toil:3.16.0a1.dev2291-f6097c0afed0a4b58b522a3021e64835a679dbd4

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-251)
┆Issue Number: TOIL-251

**Comment by joelarmstrong** [comment]
Yeah, the maxNodes/minNodes sorting is totally broken when you use multiple instance types, and the correspondence between a node and its min/max values will get messed up for certain sets of instances. It all depends on their resource requirements. The r3.8xlarge limit is being swapped with the i2.8xlarge limit.

This bug was fixed in #2114, but not sure what state that's in, I sort of forgot about all of this since I haven't had to run anything in the cloud in a while!

**Comment by glennhickey** [comment]
That explains it @joelarmstrong -- thanks for the clarification.  I may even vaguely remember you warning me about this ages ago.  It would be great to get this fixed because, as you say, those options as described in the help are completely broken in their current state.

Small aside:  I started going down this route of multiple node types in part because my i3.8xlarge spot nodes seemed to be getting lost after a day or so.  The pricing history never showed them getting more expensive than my bid.  Is there a time limit or some other dimension that you can think of that could be causing my nodes to be dropped during very long jobs?
