### ISSUE TITLE
How to change the memory options in UGE

### ISSUE THREAD

**Issue by 6br** [DataBiosphere/toil#2309]
I want to use `mem_free=MEMORY h_vmem=MEMORY` instead of `hv=MEMORY  h_vmem=MEMORY` since the option to require memory differs between SGE and UGE. Is there any command line option to change the grid engine memory option like [Canu Assembler](http://canu.readthedocs.io/en/latest/parameter-reference.html#grid-engine-configuration)?

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-318)
┆Issue Number: TOIL-318

**Comment by DailyDreaming** [comment]
Currently, one can extend the commandline options going into GridEngine by setting the `TOIL_GRIDENGINE_ARGS` environment variable.  These options will then be added here: https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/gridengine.py#L117

I've made a PR though that might be useful:  #2317.  Let me know if this seems reasonable since I don't work on grid engine very often (one other option in that PR might be to avoid any default options altogether and instead solely provide options via: `TOIL_GRIDENGINE_ARGS` for that particular command).

**Comment by 6br** [comment]
Thank you!
I prefer to provide options since the memory requirement option differs among administrators of Grid Engine. I found some configuration of grid engine requires `mem_free=MEMORY s_vmem=MEMORY` instead of `mem_free=MEMORY h_vmem=MEMORY`. It is difficult to cover all styles for memory requirements.

**Comment by DailyDreaming** [comment]
I've changed the PR so that it provides an option to override and supply your own memory arguments using `TOIL_GRIDENGINE_ARGS`.  Let me know if it works!

**Comment by 6br** [comment]
Yes, it worked well!
