### ISSUE TITLE
getWaitDuration is defined in all batch systems but remains unused

### ISSUE THREAD

**Issue by jsmedmar** [DataBiosphere/toil#2362]
Method [`getWaitDuration()`](https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L394) is defined in all batch systems but is never called in the codebase. The difference between [`getWaitDuration()`](https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L394) and [`sleepSeconds`](https://github.com/DataBiosphere/toil/blob/master/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L397) is yet not clear to me. However, I think if we don't want to overload batch systems, `statePollingWait` should somehow honor `getWaitDuration()`  [here](https://github.com/DataBiosphere/toil/blob/619fbc3e012c0081911b266ec1e5ad4e2c031142/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L184).  For example, only use `statePollingWait` if greater than `getWaitDuration()`:

```python
        def checkOnJobs(self):
            ....
            polling_wait = self.getWaitDuration()
            current_wait = (datetime.now() - self._checkOnJobsTimestamp).total_seconds()

            if self.boss.config.statePollingWait > polling_wait:
                 polling_wait = self.boss.config.statePollingWait

            if self._checkOnJobsTimestamp and current_wait < polling_wait:
                return self._checkOnJobsCache
           .... 
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-342)
┆Issue Number: TOIL-342

**Comment by DailyDreaming** [comment]
Wow, actually had to go back in time a few years to find out where/why `getWaitDuration()` was implemented:
https://github.com/DataBiosphere/toil/blob/c2b83444e6062c21d62b2f8f5b3dea32542a7c33/workflow/jobTree/bin/jobTree.py#L187

You're right, it's no longer called at all.  Rather than trying to reconcile it, I think it would be a good idea to get rid of it rather than sustain two seemingly very similar implementation when we're clearly using a new method:
https://github.com/DataBiosphere/toil/pull/1769
https://github.com/DataBiosphere/toil/pull/1892

**Comment by jsmedmar** [comment]
I was wondering that exactly, but I think its valuable that batch system implementers can have a say on how often is safe/convenient query their technology. That's why I suggested that by default `polling_wait = self.getWaitDuration()` unless the actual user want to wait more time before polling by setting `statePollingWait`.  For instance, currently the default for `statePollingWait` is 1 second, thats way to often for LSF, however the LSF implementer was aware of this and set `getWaitDuration()` to 15 seconds.

**Comment by DailyDreaming** [comment]
Hmmm... that's a really good point, and I feel the option should default to something batch specific rather than 1 every time.  What if the option defaulted to None (here: https://github.com/DataBiosphere/toil/blob/3ebfd12c86e62c99804cc17d7c8a88ceb2e7b1a7/src/toil/batchSystems/options.py#L141), and if it wasn't set in the class, it defaulted to whatever is best for that batch system?

Something like:
`self.boss.config.statePollingWait = self.boss.config.statePollingWait if self.boss.config.statePollingWait else self.getWaitDuration()`

**Comment by DailyDreaming** [comment]
@jsmedmar Also, you'd mentioned you were waiting on a release, and I was planning on it soon, was this something you wanted in the next release?

**Comment by jsmedmar** [comment]
Yes I like your solution, default `statePollingWait=None` and set: 

```python
self.boss.config.statePollingWait = self.boss.config.statePollingWait or self.getWaitDuration()
```

This makes sense. I reviewed what other implementers set for `getWaitDuration()` and there are numbers between 0 and 15 seconds. The only exception was `gridengine` which is set to 120 seconds. This nevertheless is not a big deal. Duration of bioinformatic pipelines running in clusters is usually in the order of hours or days hence a 120 second wait before polling is totally negligible. On the other side, querying a batch system every 1 second seems an unnecessary overkill that comes by default. Specially if you are running thousands of toil pipelines, which are in turn submitting thousands of jobs.
 
What do you think?

**Comment by DailyDreaming** [comment]
@jsmedmar I think 0 seconds is too short and should be at a minimum every 1 second.  I'm not opposed to extending them, though current users might see a large difference if the latest version changed to 120 seconds.  I'd rather not have it so high, though I expect most workflows don't actually need a more frequent update as you mentioned.  8 seconds sounds about right?

I'm going to be gone for the weekend so the next release will likely be on Tuesday/Wednesday.

**Comment by jsmedmar** [comment]
8-15 should be fine. The way it works is that if there are 2000 jobs running, then 2000 queries every 8/15 seconds will be run. Next week is perfect for release, enjoy the weekend!
