### ISSUE TITLE
AWS workflow autoscaling/shared resources

### ISSUE THREAD

**Issue by edraizen** [DataBiosphere/toil#2374]
I am starting to switch my workflow from slurm to AWS. Since all shared folders are accessible to every worker on slurm, I have one directory that has the toil workflow as well as all of the data that the workflow generates. Each part of the workflow modifies the data in different ways and needs to persist after the workflow has finished. 

How can I accomplish something similar on AWS? Is there a way to make each worker mount the same s3 bucket and if it doesn't exist create one?

On the sorting example, it seems that you can just run rsync-cluster to download the file once it has finished, but I didn't see anything about storing the results on an S3 bucket.

In the AWS autoscaling sections it says: "Toil also creates a bucket in S3 called aws:us-west-2:autoscaling-sort-jobstore to store intermediate job results." This makes me think what I am asking exists, but I am just not seeing it in the docs. Thanks!

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/TOIL-347)
┆Issue Number: TOIL-347

**Comment by adamnovak** [comment]
Toil doesn't do any FUSE-like mounting of AWS buckets to provide a shared filesystem in cloud environments that don't have one.

The idiomatic way to work with files in Toil is to put them in the FileStore that Toil exposes to jobs, and access them with the [FileStore API](https://toil.readthedocs.io/en/3.15.0/developingWorkflows/toilAPIFilestore.html). Basically you exchange your file for an ID, and pass that ID along to later jobs, and te later jobs can use the ID to retrieve the file, no matter what node they are running on. To get files in and out in your script's main function, you should use the [importFile](https://toil.readthedocs.io/en/3.15.0/developingWorkflows/toilAPI.html?highlight=importFile#toil.common.Toil.importFile) and [exportFile](https://toil.readthedocs.io/en/3.15.0/developingWorkflows/toilAPI.html?highlight=importFile#toil.common.Toil.exportFile) methods on the `Toil` instance you get to put files into the file store initially, and to pull them out when your workflow finishes. These can read/write to/from external S3 buckets.

It can be hard to port workflows that assume the existence of a shared filesystem to this object-based API, unfortunately. It also makes checkpointing intermediate data hard, because you have to know about everything you want to read from the outside world at the very beginning, and you can't write to the outside world until the very end, after everything succeeds. So you can only resume workflows using Toil's built-in restart system.

For applications where you want to read/write to S3 buckets or other external storage by file name name during a workflow, Toil doesn't really help you, but we've been using [`IOStore`s](https://github.com/vgteam/toil-vg/blob/master/src/toil_vg/iostore.py#L161) to provide a consistent read/write API on top of S3, Azure storage, and the local filesystem, outside of the primitives Toil gives you. We have a few different implementations of this pattern around; I'm not sure off the top of my head which would be the best one to re-use for new development. But even then it's not as simple as a shared filesystem, since everything has to be wrapped.

**Comment by edraizen** [comment]
Hey Adam! Thanks, that gives me a good idea of where to start. I'll use the IOStore and if I have more questions, I'll let you know!
