### ISSUE TITLE
Accessing the Jobstoreid corresponding to a job

### ISSUE THREAD

**Issue by psafont** [DataBiosphere/toil#2449]
Is it possible (or even reasonable) to access the JobStoreID related to a Job by going through a JobNode?

This would be helpful for the provenance recording I'm adding.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-305)
┆Issue Number: TOIL-305

**Comment by DailyDreaming** [comment]
Yes!  It is both possible and reasonable: https://github.com/DataBiosphere/toil/blob/19c1ae969487e20eb28ad1cf36976f03a701aa0c/src/toil/job.py#L201

**Comment by DailyDreaming** [comment]
@mr-c What exactly are you trying to do?

**Comment by mr-c** [comment]
@DailyDreaming Record any all metadata about job execution, including the jobStoreID, from within `Job.run()`

**Comment by DailyDreaming** [comment]
@mr-c I see, to reiterate for clarity, your problem is that `Job.run()` is a basic class without a `jobStoreID` before being converted to a `JobNode()` and being issued a `jobStoreID`, but you want to fetch this when launching the job with Job.run().  After looking around, I'm not sure it's right to fetch this information from within the run method.

This is where the jobStoreID appears to be created:
https://github.com/DataBiosphere/toil/blob/master/src/toil/leader.py#L601

You'll notice people have tacked on a log message and a metrics recording script to log the information from there as the metadata is assigned.  I think that this is the appropriate place to capture this information, possibly via some universal log file that can be checked (still not certain) or the metrics logging features already in place.

**Comment by DailyDreaming** [comment]
Stale, closing.  Please reopen if this is still an issue.

**Comment by mr-c** [comment]
Still needed for CWLProv
