### ISSUE TITLE
Timestamps are not set in the Mesos dashboard

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2526]
Timestamps are not set in the Mesos dashboard (localhost:5050) when trying the CWL runner on AWS. It shows "49 years ago" (aka epoch) for everything.

I think it's caused by [this commit](https://github.com/DataBiosphere/toil/commit/8efb7cabcc04b3b052cc1d8a1319ca19d260d723) as the build from the previous commit (just after the 3.18.0 release) works fine, but i haven't figured out the root cause yet.

@adamnovak FYI, in case you have any ideas.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-51)
┆Issue Number: TOIL-51

**Comment by adamnovak** [comment]
Yeah, I noticed something like this when originally working on the
Pymesos stuff. I guess I forgot to fix it.

Toil is using *relative* timestamps on everything it is feeding to
Mesos. It needs to be changed to use *absolute* timestamps, so that
Mesos doesn't think we started doing everything at midnight on Jan 1
1970.

We need to find every timestamp that our Mesos-using code sends, and convert it.
