### ISSUE TITLE
Network error (ST_KV_DATABASE_EXCEPTION) while running Cactus with Toil on an SGE cluster

### ISSUE THREAD

**Issue by amizeranschi** [DataBiosphere/toil#2530]
Hello,

I've posted a detailed report on the Cactus issue tracker, but I wanted to link it here as well, in case it's somehow a Toil issue: https://github.com/ComparativeGenomicsToolkit/cactus/issues/63

I'm running a minimal Cactus example, which works fine on a single node when submitted via qsub, but fails when attempting to distribute on multiple nodes.

Any ideas about how to deal with this would be greatly appreciated.

**Comment by adamnovak** [comment]
I don't *think* this is a Toil issue. The network error is caused by your database server having crashed and not being connectable, and the real mystery is why the database server crashes. It might be an issue with how Cactus is starting up KT, but I don't think it's an issue with Toil specifically.

**Comment by amizeranschi** [comment]
Yes, you're probably right that it's not a Toil issue. I'll close this thread here.
