### ISSUE TITLE
Logging is setup too late

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/toil#254]
If Job.wrapJobFn causes a log entry, the following message is logged instead: 

```
No handlers could be found for logger "toil.resource"
```

```
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-306)
┆Issue Number: TOIL-306

**Comment by cket** [comment]
What behavior do we want here? Would a user expect a method call like this to create its own handler?
Another small complication is that logging level is determined by toil options, which are not accessible in the object and may not have been parsed yet. I think a null handler might be the best thing here, since the alternative seems to be defining an actual handler whose level may not agree with what the user specifies.

**Comment by cket** [comment]
Add toil context to insure log handlers are set up before toil is run

**Comment by hannes-ucsc** [comment]
New `Toil` context manager may make implementing this easier.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still relevant.
