### ISSUE TITLE
Enable caching on grid engine (optimize hard links and copying to reduce redundancy).

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#2551]
See #2534.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-47)
┆Issue Number: TOIL-47

**Comment by adamnovak** [comment]
OK, I'm trying to come up with a coherent linking system, and we have a problem.

For the caching file store, it relies on being able to get hardlinks into the job store. If you link imports, some of the files in the job store may be symlinks to files on other devices, while some may be actual files. On Mac, you can't hardlink to a symlink; you will hardlink to the underlying file instead. So you can be in a situation where all the files in the job store can be hardlinked over to the cache *except* for the ones on other devices, included via symlink. Additionally, those symlinked-in files may have unexpectedly high link counts, which will upset the caching file store. You can also be in a situation where most of the files in the job store *can't* be symlinked over to the cache, except for some that *can*, because they're symlinks back onto the device where the cache is.

The caching file store is not clever enough to deal with this. If there are any symlinks in the job store on Mac, we can't safely assume that the job store accounts for all the space usage of cached files, for example, even if we can successfully hard links test files out of it.

We have to do one of:

- Replace link count based reference counting with real reference counting that we do ourselves, so we can deal with a mix of links and copies in the cache
- Avoid cross-device symlinking into the job store on Mac
- Always copy from the file store to the cache on Mac, even when we could link.

I think the last one makes the most sense. There's no good reason to use the caching file store with the file job store anyway, unless you're in some kind of HPC environment where Mac probably isn't, so while this will increase disk usage of that configuration on Mac, that configuration should be relatively uncommon.

**Comment by adamnovak** [comment]
The approach I am taking is to always make mutable copies into the cache on Mac. I have code that should handle everything else as hard links to either real files or symlinks depending on what's in the file job store, and which should de-symlink thangs when the user asks to not have a symlink.

**Comment by adamnovak** [comment]
OK, I'm not really sure it makes sense to try and do this without basically redoing the `CachingFileStore`. It's not clear to me how that class accounts for space, and all its behavior relies on somewhat implicit assumptions about what it gets from the different job store implementations.

We should work out exactly what the disk space usage model is right now: is it doing all this fiddly work with space usage to enable us to track how much disk space a job *would have* used without caching, to support warnings to the user if it is too high? Or is it trying to keep the disk usage of the cache under the disk usage allotments of all the current jobs? When an asynchronous upload starts, and the job that started it finishes before it does, who owns the disk space usage of the file in the process of being uploaded? Can a followon job start via chaining and immediately fill the disk requirement safely? What do the tests try to enforce, and what do we want to guarantee?

We should also work out if we can get informed when jobs finish, so we can reference count ourselves instead of trying to delegate to the filesystem. If we could give jobs symlinks instead of hard links we wouldn't have to worry about cross-device copies, but we can only do that if we can do our own reference counting.

**Comment by adamnovak** [comment]
I*'m going to reopen this because #2570 is garnering some discussion again.

I think the task is now to fix things so that when you run a workflow with default settings on grid engine, with the FileJobStore on NFS and the Toil work directory on local temp directories, you don't get loads and loads of copies of the same file when all your jobs try and download it.

That might look like enabling caching on grid engine and turning it on by default, or it might look like defaulting to `symlink=True` and hoping people using Docker change it to `False`, or it might look like something else.

It also couldn't hurt to support hard links out of the FileJobStore where possible.

**Comment by adamnovak** [comment]
I'm going to see if I can make progress on this today.

**Comment by adamnovak** [comment]
I think #3055 and #3047 (which are basically the same task) might end up fixing this.
