### ISSUE TITLE
Caching is disabled by default and no way to turn it on

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2586]
Caching is currently disabled by default ( from https://github.com/DataBiosphere/toil/commit/2e54371ea316fe2803ce53d1477a51fadcfb5d2e ) and there is no way to turn it on.

Options:
* Change the default value of `disableCaching` back to False
* Add an `enableCaching` option to preserve the current default behavior.

**Comment by DailyDreaming** [comment]
First, caching has some issues unfortunately so the default should remain to leave it off until someone has the time to reproduce and fix them.

Second, if it can't be turned on, that's a bug.  There should be one option to either enable or disable caching, so I think the best option is to make it so that setting `disableCaching=True` actually allows for caching.

**Comment by adamnovak** [comment]
Erm, isn't that disableCaching=False to turn caching on?

**Comment by arostamianfar** [comment]
Sounds good! I updated PR #2584 to add `disableCaching=False` and leave the default as is.
I like to understand the issues around caching though and help out in fixing them! We can discuss more offline.
