### ISSUE TITLE
Toil does not report that jobs time out

### ISSUE THREAD

**Issue by lassancejm** [DataBiosphere/toil#2642]
Hi, 

I am using toil 3.19 with a cluster using Slurm to schedule jobs. 

I am noticing that some jobs keep being resubmitted over and over again after they time out.

I can increase the time specified using TOIL_SLURM_ARGS, but it would be nice to have Toil not submitting these jobs indefinitely and reporting that they cannot be completed given the current settings. 

Thanks

JM

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-5)
┆friendlyId: TOIL-5

**Comment by adamnovak** [comment]
Toil has no internal idea of a timeout for a job, and if the Toil code
that gets scheduled to load and run the job dies before actually
detecting and managing to report an error that is the job's fault, the
Toil leader will just re-run the job.

The timeout in this case is Slurm imposing a maximum runtime on the
jobs that you schedule, and just killing the process it invoked (i.e.
the Toil worker) when that limit is hit, right?

How does that get reported by Slurm back to whatever scheduled the
job? I think we would have to detect that and then manually mark the
job as failed from the leader, instead of rescheduling it, to make
this work.

Also, if your scheduler imposes a runtime limit, you probably want to
pass `--disableChaining`, so that jobs are all scheduled individually
with the scheduler. By default Toil can run a series of related jobs
in a single scheduling operation, which can lead to long-running
processes from Slurm's point of view.

**Comment by jsmedmar** [comment]
We solved this problem for `LSF` at [Toil Container](https://github.com/papaemmelab/toil_container). 

We wrote a `batchSystem` that detects jobs failed due to RUNTIME and MEMORY and resubmits them with appropriate resources: https://github.com/papaemmelab/toil_container/blob/2afa80080fc83a34491cd80efe05159ddc386729/toil_container/lsf.py#L55

Our `ContainerJob` class allows to pass `runtime` on a per-job basis: https://github.com/papaemmelab/toil_container/blob/master/toil_container/jobs.py#L18

You could perhaps do something similar for SLURM?

**Comment by lassancejm** [comment]
It turns out that the exit code for a job timing out is zero, so it looks as if it didn't fail for Toil. 

Maybe passing a non-zero exit code is the state is TIMEOUT would make sense. 

https://github.com/DataBiosphere/toil/blob/fa69a4436a154d4fd7d6dc8fed4fa0e16c802e34/src/toil/batchSystems/slurm.py#L78-L91

**Comment by adamnovak** [comment]
Yeah, that might help. It looks like the exit code eventually makes
its way to https://github.com/DataBiosphere/toil/blob/fef89da0fbea451d7dc458ee56e7d96dd871374b/src/toil/leader.py#L490-L498
to be checked, and a nonzero value indicates job failure.

Can you develop and test a patch? We don't have a cluster with
timeouts to test on here at UCSC.

**Comment by ckandoth** [comment]
[Here's](https://github.com/mllg/batchtools/issues/196#issuecomment-393925058) some more info for anyone with the bandwidth to patch this. Toil uses `squeue` [here](https://github.com/DataBiosphere/toil/blob/releases/3.21.0/src/toil/batchSystems/slurm.py#L49) to get the status of each job, but `sacct` is preferable for its ability to distinguish `TO TIMEOUT` jobs from `Done` jobs.

**Comment by Hexotical** [comment]
I've tried to replicate this but cannot, we appear to be using sacct now which gets the appropriate status.
