### ISSUE TITLE
Fix gitlab docker runner.

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2652]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-352)
┆Issue Number: TOIL-352
┆Epic: Better Testing

**Comment by adamnovak** [comment]
We're not getting Python 3 tests passing on the Gitlab runner, because our locale on the machines is preventing Python from being willing to print anything to standard output that isn't in ASCII. We have to set PYTHONIOENCODING=utf-8, or set the locale to something where `python -c` thinks it can print Unicode to the terminal.
