### ISSUE TITLE
Reimplement caching to be aware of which files it needs to keep (be aware of active jobs; reference counting).

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/toil#2691]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-369)
┆Issue Number: TOIL-369

**Comment by adamnovak** [comment]
OK, I have gotten started on this in issues/2691-revise-caching by breaking out the different fileStore implementations into their own files and trying to document the FileStore API a bit better.

In addition to actually being a FileStore, the FileStore also does a few other things:

* It handles non-real-time, reliable logging to master.

* It lets you find your local temp directory.

* It provides import and export functions for external URLs.

* It tracks all the jobs currently running on the machine, no matter how many workers there are sharing the machine. Even the non-caching version keeps job state files. It uses this to implement the whole deferred function system, which looks to the user like it is on the Job, but is really implemented by calling into a seemingly private method on the FileStore behind the scenes. The FileStore then uses the context manager that I think it acquired when caching was added to make sure that the deferred functions are run when the job finishes. But if the whole worker dies, any other worker running on the same machine will check for outstanding deferred functions and run them.

I think that this functionality needs to be split up a bit before I can actually do anything to the caching logic. The deferred function system needs to be split out; there's no reason I can see that we should have two full implementations of it in the caching and non-caching FileStores. This probably means we will get some kind of LocalNodeJobStateTracker, with its own context manager that the worker needs to enter, which is just responsible for answering which jobs are currently running and which have deferred functions that need to happen. I'd like to use a real (SQLite) database for this and for the cache state, instead of flat files.

I'm also not sure the existing system of PID polling to detect dead workers is robust enough to PID re-use. We might want something like a file per job where the worker running the job keeps an fnctl or flock lock on it as long as it is alive, and everybody else periodically polls for files that are not locked.
