### ISSUE TITLE
cwltoil: missing MultipleInputFeatureRequirement does not raise error

### ISSUE THREAD

**Issue by kaushik-work** [DataBiosphere/toil#2701]
A workflow that has multiple inbound links but no `MultipleInputFeatureRequirement` runs fine in `Toil` but not in `cwltool`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-376)
┆Issue Number: TOIL-376

**Comment by adamnovak** [comment]
So the error here is that we are failing to reject an invalid CWL file, which the CWL spec requires us to reject?

It looks like there's no test for this in the CWL conformance tests: https://github.com/common-workflow-language/common-workflow-language/issues/569 was closed because the requirement to reject these workflows is (maybe?) going to be removed in CWL 1.1.

**Comment by DailyDreaming** [comment]
Based on @adamnovak 's comment, this issue is likely both stale and not in need of fixing.  Please reopen if this is still an issue.
