### ISSUE TITLE
--targetTime for Slurm?  Cactus/Toil impacting Slurm

### ISSUE THREAD

**Issue by jasonsydes** [DataBiosphere/toil#2712]
Hello Toil/Cactus community!

I rewrote a bit of toil/batchSystems/slurm.py, and by doing so, I was able to resolve #2323; with my patch, Toil is able to effectively immediately hand off jobs to Slurm, and Slurm is now the bottleneck.

Unfortunately, this appears to be causing some problems with our Slurm installation; it may be more than it can handle.  I haven't been given too many details, but from what I've been told, the problems stem from cactus/toil launching thousands and thousands of very short jobs.  These short jobs are less than 30 seconds long, and they are apparently straining the system.  I've been told that my current cactus run launched 250,000 jobs that were less than 30 seconds long on Sunday.

One of our HPC's system administrators suggested we try --targetTime, but we've looked into it, and it appears that code is only applicable if you're using auto-scaling clusters (e.g. AWS).  He's now looking to see if there's something he could do (presumably some Toil code he could tweak / write) to alleviate the problem.   

Would it be possible to port the --targetTime code over to Toil's Slurm / BatchSystem code?  If so, is this something you could do?  If it's not something you could soon, do you think it would be difficult for us to do?  I took a quick glance at it, and it doesn't look trivial.  I haven't looked deep enough yet to determine whether it would be doable.  If you have any advice on how to move forward, we would love to hear it.

For reference, here's the help on --targetTime:
```
  --targetTime TARGETTIME
                        Sets how rapidly you aim to complete jobs in seconds.
                        Shorter times mean more aggressive parallelization.
                        The autoscaler attempts to scale up/down so that it
                        expects all queued jobs will complete within
                        targetTime seconds. default=1800
```
Of course, a solution does not necessarily require that --targetTime be ported over to the batchSystems code.  Anything that could reduce the number of small jobs would work.   We would love to hear any suggestions you might have.

Thank you for your time!!!
Jason

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-382)
┆Issue Number: TOIL-382

**Comment by jasonsydes** [comment]
I should clarify the severity of the problem.  Our HPC staff asked us to terminate our cactus run for the time being.

**Comment by adamnovak** [comment]
I believe that `--targetTime` only influences the autoscaler's strategic decisions about how many nodes to have. If you shorten the `--targetTime`, it will try and create more nodes, to the point where it thinks it has enough nodes to do all the work outstanding in `--targetTime` seconds.

It has no effect on the granularity/size of the jobs themselves, or on how many it is willing to feed to the batch system at a time.

The small size of the jobs isn't really Toil's fault; beyond some "chaining" logic that Toil uses to run immediate successor jobs opportunistically without feeding them back through Slurm, Toil just presents the jobs to Slurm as they were given to Toil. If Cactus needs to run thousands of 30-second jobs, and that pattern is bad for Slurm, then Cactus maybe needs to be modified to break up its work differently, into fewer, longer-running chunks.

Alternately, Toil could be given some code to coalesce jobs that aren't immediate successors, so you could send one job to Slurm which, upon execution, actually runs several Toil jobs of the same size in a row. But to do that well, Toil would need to know how many jobs Slurm wants to be running in parallel; there's no sense coalescing jobs to the point where you're leaving nodes idle. Plus, the bookkeeping involved would be a lot of work.

I think what you might really want, though, is to just limit the maximum number of jobs that Toil will queue up in Slurm at a time. Your problem might not be that the jobs are short and numerous, but that Slurm has to manage too many of them at once. Based on [the code that decided whether to send jobs to Slurm](https://github.com/DataBiosphere/toil/blob/e36c2f23d075e46582c000947fb27c400355bf86/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L129-L131), you might be looking for the `--maxLocalJobs` option, to limit the total outstanding jobs submitted to Slurm, even though the help documentation for it claims that it means something completely different.

Maybe @DailyDreaming can clarify whether the semantics of this option are correctly documented/implemented, and why/where the `AbstractGridEngineBatchSystem.Worker` class is used. I can't figure out if we're running one of these per Toil worker, and each worker is only allowed to send in so many jobs at a time, or if we really have just the one instance on the leader. In any case I suspect the option documentation is wrong, because if this is just the "local" job submission logic, where is the non-local job submission logic?

**Comment by DailyDreaming** [comment]
@adamnovak You interpretation seems accurate to me.  `--targetTime` is currently only in our cloud autoscaling code, and `--maxLocalJobs` is in fact mislabeled and should probably be corrected.

@jasonsydes It might be possible to add something analogous to `--targetTime` for clusters, however, as Adam mentioned, this might be something that makes more sense to change in Cactus (being the workflow defining these tasks) itself.  @joelarmstrong do you know of options within cactus that might help with reducing the number of small jobs?

**Comment by michaelkarlcoleman** [comment]
Hi, I'm the colleague of @jasonsydes that helps run the SLURM cluster.  I agree with @adamnovak that the fundamental problem is really with Cactus (possibly compounded by some oddity of or degeneracy in the input data).  Looking there now, but here are a few thoughts.

First, although having a large number of SLURM jobs enqueued can be a problem, simply _running_ a huge number of (very short) jobs is an additional headache.  SLURM captures a fair amount of metadata about each job, has to spend time thinking about it, etc.  This is an additional and significant problem, so throttling enqueued jobs is not enough.  I'm not sure how the Toil AWS backend works, but I suspect that firing hundreds of thousands of tiny jobs onto AWS worker hosts may well be less than ideal, for similar reasons (even if the overhead is lower).

As a possible Toil feature enhancement, it might be possible to add a feature to coalesce jobs, as @adamnovak mentioned.  This might not be as hard as it sounds.  You'd need a way to crawl the job graph to assemble dependency-compatible work packets of an "about right" size (two or five minutes?), and a way to specify how many "slots" in SLURM (or whatever backend) you're trying to fill.  The primary thing missing is a way for the caller to tag each task with an estimated running time, so that work packets of proper running time can be built.

The nice thing about that feature is that the calling software doesn't have to "pre-schedule" tasks before handing them off to Toil.  Toil can handle the whole mess.

**Comment by jasonsydes** [comment]
Hi all,

Thanks for all your input, I'm following all your thoughts.  I don't have anything to add at the moment, but I'll go ahead and attach my toil stats from our recent 13way run; perhaps it'll be useful for this:

[toil_stats_13way.txt](https://github.com/DataBiosphere/toil/files/3288288/toil_stats_13way.txt)

I'm currently running toil stats on our larger run that @michaelkarlcoleman and crew asked us to terminate, I'll post that here when it's complete.

**Comment by jasonsydes** [comment]
Here's the stats from our larger (but incomplete) run with many more species (ran for multiple days, then stopped it).

[toil_stats_bigway.txt](https://github.com/DataBiosphere/toil/files/3291683/toil_stats_bigway.txt)

**Comment by jasonsydes** [comment]
These ones seem to be the worst offenders:
```
 RunBlast
    Count |                                            Time*
        n |      min     med*      ave       max       total
   241573 |     0.44   156.99   179.74   1144.95 43419185.16
 CactusHalGeneratorRecursion
    Count |                                            Time*
        n |      min     med*      ave       max       total
   235855 |     0.03     0.18     0.30    125.27    70969.61
 CactusHalGeneratorUpWrapper
    Count |                                            Time*
        n |      min     med*      ave       max       total
   235851 |     0.02     0.30     0.93    120.32   219153.03
 CactusSetReferenceCoordinatesDownWrapper
    Count |                                            Time*
        n |      min     med*      ave       max       total
   115639 |     0.02     0.51     0.96    108.52   110510.15
 CactusSetReferenceCoordinatesUpWrapper
    Count |                                            Time*
        n |      min     med*      ave       max       total
    96983 |     0.02     0.70     3.57    271.82   346431.40
 CactusReferenceWrapper
    Count |                                            Time*
        n |      min     med*      ave       max       total
    96983 |     0.02     0.71     1.44    347.33   139941.17
```

**Comment by jasonsydes** [comment]
Hrm, so, I'm reading a bit about how cactus/toil can run on Mesos.  And reading about Mesos here:

https://people.eecs.berkeley.edu/~alig/papers/mesos.pdf

And it seems like Mesos might be specifically built (optimized even??) for lots of "short jobs".  As in, these tiny jobs are bring Slurm to its knees, but maybe Mesos thrives in such an environment??

It appears that all of your cloud code runs on top of a Mesos cluster?  I'm wondering if we should be trying to get a temporary Mesos cluster spun up on top of a Slurm allocation of nodes, and run Cactus/Toil on top of that temporary Mesos cluster.  

I'm guessing that when your group does a cactus run, you're doing it in the cloud, which is running with Mesos, and you're not experiencing the same kind of problems with lots and lots of small jobs?

**Comment by adamnovak** [comment]
We do run a lot of Toil things on Mesos, including Cactus, and we've
never that I know of had a problem with jobs being too short for
Mesos.

If you can figure out how to schedule a Mesos cluster on top of your
Slurm cluster, that could indeed be a workaround.

**Comment by jasonsydes** [comment]
Thanks for the response @adamnovak!  I met with @michaelkarlcoleman today, and we're looking at two or three different solutions, and running Mesos on top of Slurm is one of them.  

Before we go too deep down that Mesos/Slurm path, could we ask, do you expect Mesos to run OK independently of a provisioner.  In other words, do you expect (have you tested?) running Mesos *without* AWS / GoogleCloud? Are there provisioner libraries or APIs that Mesos depends upon that will cause it to fail if we run it outside of a cloud system?

I'm certainly seeing in various places (documentation, Github Issues, peeking cactus/toil code) that Cactus will run with Mesos if it's running alongside AWS / Google Cloud.  But, it seems less apparent that Mesos is supported by itself?  

For example, on this *old* [documentation page](https://toil.readthedocs.io/en/releases-3.1.x/essentials.html), I see you can deploy Toil on: _High Performance Computing Environments + GridEngine + Apache Mesos + Parasol + Individual multi-core machines_ .  But [newer documentation](https://github.com/ComparativeGenomicsToolkit/cactus) doesn't list Mesos among the other HPC batch systems (i.e.  _LSF, SLURM, GridEngine, Parasol, and Torque_), and Mesos isn't listed on the Cactus home page at all.  (Our cluster is down for scheduled maintenance today, so I can't check, but I believe I remember cactus --help saying that "--batchSystem mesos" was an option).

Thank you for your time!!
Jason

**Comment by adamnovak** [comment]
I've used Mesos without a provisioner with the (old) Azure cluster
template setup, where you deploy a fixed-sized Mesos-managed cluster.
It worked fine for me. Toil's provisioning logic is pretty well
self-contained, and Mesos doesn't need a provisioner of its own, or
anything cloud-specific. It may need more user permissions than your
cluster will give you, however, depending on how you want it set up.
For example, I think you can set it to sandbox jobs with cgroups, but
it can't do that if it can't control cgroups.

I think we don't list Mesos with the HPC batch systems because it
isn't really an HPC batch system. There's no submission command that
Toil runs to talk to it; we interface directly with its HTTP API.

Not that many people actually have Mesos clusters, either, so maybe
that's why Cactus doesn't mention it.

**Comment by adamnovak** [comment]
Cactus now has a way to run with much larger individual jobs, and `--targetTime` can't do what this issue wanted it to do, so I am going to close this out.

@jasonsydes We'd still be interested in your #2323 fix if you have it handy.
