### ISSUE TITLE
Toil logs are linked to one another

### ISSUE THREAD

**Issue by ionox0** [DataBiosphere/toil#2713]
I was wondering if anyone could answer for me what it means for Toil logs to be linked to one another? For example in the following screenshot:

<img width="1440" alt="Screen Shot 2019-06-13 at 6 17 21 PM" src="https://user-images.githubusercontent.com/6385646/59471019-bc810c80-8e07-11e9-8fcd-7c92df59c682.png">

Does this happen when one job is a follow-on job of another?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-383)
┆Issue Number: TOIL-383

**Comment by adamnovak** [comment]
More or less.

The relevant code is here:

https://github.com/DataBiosphere/toil/blob/8bcdb4519319ae4e43136ff836ef07959cef242b/src/toil/statsAndLogging.py#L102-L106

Symlinks happen when one log file contains output from multiple jobs. This in turn happens when jobs are "chained", which happens when exactly one successor to the job exists and it can be run inside the previous job's resource requirements. The chained jobs' filenames link to the original file created for the parent job, which has output for both.
