### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by gconcepcion** [DataBiosphere/toil#2793]
Hello,

I see [this old bug](https://github.com/DataBiosphere/toil/issues/427
) addressing something similar, but doesn't seem to help me out here?

I'm running genome alignment software Cactus and running into the UnicodeDecodeError with toil below

any advice for continuing?

```INFO:toil.leader:Reissued any over long jobs
Traceback (most recent call last):
  File "/home/UNIXHOME/gconcepcion/venvs/cat/bin/_toil_worker", line 10, in <module>
    sys.exit(main())
  File "/home/UNIXHOME/gconcepcion/venvs/cat/lib/python2.7/site-packages/toil/worker.py", line 536, in main
    workerScript(jobStore, config, jobName, jobStoreID)
  File "/home/UNIXHOME/gconcepcion/venvs/cat/lib/python2.7/site-packages/toil/worker.py", line 483, in workerScript
    w.write(f.read().encode('utf-8')) # TODO load file using a buffer
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1939: ordinal not in range(128)
ERROR:toil.batchSystems.singleMachine:Got exit code 1 (indicating failure) from job /home/UNIXHOME/gconcepcion/venvs/cat/bin/_toil_worker mappingQualityRescoring file:/pbi/dept/bifx/gconcepcion/PBFT_CCS/16kb/cat/output 6/l/jobu54VgD.                                                                                                                                                                               
WARNING:toil.leader:Job failed with exit value 1: 'mappingQualityRescoring' 6/l/jobu54VgD```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-418)
┆Issue Number: TOIL-418

**Comment by adamnovak** [comment]
Hm. I suppose you are running on Python 2?

I think we re-introduced #427 with recent changes to log data manipulation. We changed from reading log data as bytes to reading it as text, at least on Python 3. Which means we have to encode it on output.

The problem is that Cactus is still dumping high-value characters into its log output. We're trying to encode the data as UTF-8, but it isn't valid ASCII when we read it in, so we're not sure what the characters we're trying to encode are supposed to be.

We can probably fix this for Python 3 by adding a particular input encoding, specifying that bad characters should be skipped, at https://github.com/DataBiosphere/toil/blob/8e1d8c0f45f6210bbd0900380b62c5a1c1a6cdc7/src/toil/worker.py#L488

For Python 2, though, those arguments aren't available. Maybe we have to go back to binary mode here for the log processing, and decode (skipping errors) and re-encode the data manually.

**Comment by gconcepcion** [comment]
Yes - sorry - that solution sounds reasonable - but probably unnecessary as this turned out to all be a symptom of my TMPDIR getting filled. Changing TMPDIR to a location with much more space solved my problem.

Thanks!

**Comment by adamnovak** [comment]
I think we still need to fix this. The broken code only gets invoked during error handling for a failed job with a large log file, but Toil expects user jobs to fail and needs to properly collect and report the failures.

**Comment by DailyDreaming** [comment]
I can't find `w.write(f.read().encode('utf-8'))` in `worker.py` anymore.  Since this is stale and we've fixed a lot of this for py2/3 and no longer run py2, I'm closing this.  Please reopen if this is still an issue.
