### ISSUE TITLE
GA4HG TES/WES support

### ISSUE THREAD

**Issue by matthdsm** [DataBiosphere/toil#2830]
Hi,

Are there still plans to support TES in toil? 

Thanks
M

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-442)
┆Epic: MVP - Implement Toil engine prototype
┆Issue Number: TOIL-442

**Comment by DailyDreaming** [comment]
@matthdsm Yes, I'd say this is still on the roadmap if we want to integrate with dockstore, although not this quarter.  Proof of concept implementation will likely start here:
https://github.com/common-workflow-language/workflow-service

And be tested with:
https://github.com/ga4gh/cloud-interop-testing

Current priorities that take precedence include kubernetes support, improved wdl support, and refactoring/shoring up testing.  We will revisit the roadmap at the end of the year and reassess.

**Comment by mr-c** [comment]
Why was this issue closed?

**Comment by adamnovak** [comment]
Lon and I were going through issues on Jira. We marked this as
"wontfix", but then thought better of it and put it in the "icebox" of
things we don't have time to do; Jira either failed to sync that or
wrongly thinks "icebox" is a kind of "closed".

**Comment by uniqueg** [comment]
Hi, Alex here from [ELIXIR Cloud](https://github.com/elixir-cloud-aai/elixir-cloud-aai). We are interested in having a well-supported workflow engine for CWL (other languages are a bonus), but we would absolutely need TES support (and ideally a WES shim as well) to integrate with our cloud environment. We could probably provide you with a WES shim for Toil, based on or replacing [cwl-WES](https://github.com/elixir-cloud-aai/cwl-WES) which uses [`cwl-tes`](https://github.com/ohsu-comp-bio/cwl-tes) as a runner currently, but which is not well maintained, and work with you towards integrating TES support, based on what `cwl-tes` offers as of now. The latter point would need to be implemented first, though, for us to be able to make use of Toil, so that would be higher priority. Plus I'm afraid we could only provide the initial support for TES (might be different for WES, which we are maintaining anyway), as we wouldn't have the capacity to maintain a backend moving forward. It's just really not our field of expertise, which is precisely why we want to move away from `cwl-tes`...

If you are interested to discuss this, please let me know and we could schedule a meeting :)

**Comment by uniqueg** [comment]
Wanted to bump this to hopefully get some feedback from code owners? @adamnovak @DailyDreaming
Don't want to spam, but it looks like Cromwell, Nextflow and now Snakemake all have at least some rudimentary TES (and some have WES) support, and we're working with Galaxy to get there, too. Would be really nice to have a strong CWL runner that plays nice with the GA4GH Cloud APIs...

**Comment by mr-c** [comment]
@uniqueg Could you mentor a GSoC project for this?

**Comment by DailyDreaming** [comment]
@uniqueg We have plans for TES, and a prototype WES server (dev branch is: 3290-add-server-mode ).  Should have a better timeline for TES support after a meeting we're having this Friday, but the WES support is sort of done, but needs testing/vetting, and documentation.

**Comment by uniqueg** [comment]
@mr-c Damn, didn't see this on time and now the proposals are in. Sorry about that, would have been great. There may still be GSoC candidates interested in implementing this (we have a proposal on adding TES to Galaxy).

@DailyDreaming That's fantastic! If there's anything where we can help, please let me know :)

**Comment by mr-c** [comment]
> @mr-c Damn, didn't see this on time and now the proposals are in. 

The deadline was for organizations applying to be hosts for GSoC. Once they are chosen they can add additional proposals to attract interest from students.

**Comment by uniqueg** [comment]
That's true @mr-c, but it's not how it's been working within the GA4GH GSoC org, and as a sort of guest under that org I don't feel comfortable updating the ideas list at this point, especially because almost half of the suggested projects are already under the ELIXIR umbrella.

**Comment by mr-c** [comment]
@uniqueg Should you identify someone to be a potential mentor, you are welcome to add this idea to the Open Bioinformatics Foundation GSoC list

**Comment by uniqueg** [comment]
That's great. Would anyone on here perhaps be willing to serve as the primary mentor? If availability is an issue: I'm fine if that person serves as the mentor really only on paper, with very little hands-on time (would need to forward me application emails and fill out the evaluation twice, which is ~5 min each). We have quite a big mentor pool and we could mentor the project along with the others (there would be a lot of overlap with mentoring the Galaxy/TES project anyway). Our problem is that our 3 most active people are already serving as primary mentors and thus do not qualify.
