### ISSUE TITLE
"database is locked" error when using the new SQLite caching db

### ISSUE THREAD

**Issue by arostamianfar** [DataBiosphere/toil#2910]
The new SQLite-based caching keeps failing when there are several tasks running on the same worker (stack trace below). Looks like SQLite can't handle many concurrent calls (see https://stackoverflow.com/questions/26862809/operational-error-database-is-locked/26864360 ).

@adamnovak not sure if there is an easy way to limit concurrency as workers are on different processes. Perhaps the easiest thing could be to retry with a random exponential backoff and also increase the timeout as suggested in the thread? 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cwltool/executors.py", line 168, in run_jobs
    for job in jobiter:
  File "/usr/local/lib/python2.7/dist-packages/cwltool/command_line_tool.py", line 455, in job
    reffiles, builder.stagedir, runtimeContext, True)
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 274, in make_path_mapper
    runtimeContext.toil_get_file)
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 228, in __init__
    referenced_files, basedir, stagedir, separateDirs=separateDirs)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 262, in __init__
    self.setup(dedup(referenced_files), basedir)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 319, in setup
    self.visit(fob, stagedir, basedir, copy=fob.get("writable"), staged=True)
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 262, in visit
    stagedir, basedir, copy=copy, staged=staged)
  File "/usr/local/lib/python2.7/dist-packages/cwltool/pathmapper.py", line 267, in visitlisting
    self.visit(ld, stagedir, basedir, copy=ld.get("writable", copy), staged=staged)
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 255, in visit
    resolved = self.get_file(loc) if self.get_file else loc
  File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 309, in toil_get_file
    src_path = file_store.readGlobalFile(FileID.unpack(file_store_id[7:]))
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 1060, in readGlobalFile
    return self._readGlobalFileWithCache(fileStoreID, localFilePath, symlink, readerID)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 1427, in _readGlobalFileWithCache
    (fileStoreID, cachedPath, self.getGlobalFileSize(fileStoreID), 'downloading', pid))
OperationalError: database is locked
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 369, in workerScript
    fileStore.startCommit(jobState=False)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 959, in open
    self._deallocateSpaceForJob()
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 795, in _deallocateSpaceForJob
    self._removeJob(self.con, self.cur, self.jobID)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 762, in _removeJob
    for row in cur.execute('SELECT tempdir FROM jobs WHERE id = ?', (jobID,)):
OperationalError: database is locked
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-481)
┆Issue Number: TOIL-481

**Comment by arostamianfar** [comment]
Actually, increasing the timeout to 60s substantially reduced the errors, so we may be ok by just increasing the timeout for now. But lemme know if you have other ideas around reducing the concurrency and/or number of operations.

**Comment by adamnovak** [comment]
The database is *supposed* to be locked, I think; I'm relying on
SQLite's locking and internal concurrency control to keep all the
workers synchronized.

It could be that we have some piece of code that is holding a write
lock on the database for much longer than it should be (i.e. starting
a batch of writes but not committing in a timely fashion because it is
running some other code). I'm not sure how we'd hunt for that, other
than by reading through the code looking for places where that might
happen. It would be touch to pause all the other workers and find the
one holding the lock and what it is doing. Maybe we could get
everybody to announce their locks/unlocks with the real time logger
somehow.

**Comment by diekhans** [comment]
In addition to tracking down who is hogging the lock, putting
the write locking in a retry loop would be useful.  It can be
very hard to get a timeout right when process can slow down for
unpredictable reasons.

**Comment by arostamianfar** [comment]
Both sound good! Any objections to increasing the timeout to 60s in the meantime? That substantially reduces the errors while we investigate the root cause(s).

**Comment by adamnovak** [comment]
That's definitely a good idea @arostamianfar; I suppose you know where it is configured?

**Comment by arostamianfar** [comment]
yeap; sent PR #2913

**Comment by adamnovak** [comment]
One potential cause here is this part of `_giveAwayDownloadingFile` where it makes a change to the database but never commits to close out the transaction: https://github.com/DataBiosphere/toil/blob/07af6913e73199193be7bcf290c2dedbc7f82d2d/src/toil/fileStores/cachingFileStore.py#L1360-L1365

**Comment by arostamianfar** [comment]
@adamnovak i think we can close this issue? I haven't seen the error since merging both changes. Thanks for your help!

**Comment by adamnovak** [comment]
Excellent. I will close this up.

**Comment by arostamianfar** [comment]
I was able to reliably reproduce this again on a new workflow that operates on large (100GiB+) files. I haven't yet looked into the details on why the exception happens, but I think the reproducible scenario is like:
* Job 1 runs on worker `A` and outputs a large file, `F`.
* After job 1 finishes, job 2 runs on worker `B` and uses `F`. Starts downloading the file from s3 (takes 15+ mins).
* Job 3 runs on worker `B` while `F` is being downloaded.

@adamnovak do see any obvious places where the lock can be held while a file is being downloaded?

**Comment by pgrosu** [comment]
Based on Asha's description you have this:

`{ Job_3[Worker_B], Job_2[Worker_B](Job_1[Worker_A] -> F) }`

Usually you want to have the cache travel to get around deadlocks as such:

`{ Job_3[Worker_B](Cache_Copy_3), Job_2[Worker_B](Job_1[Worker_A](Cache_Copy_1) -> F, Cache_Copy_2) }`

Think of it as message-passing a copy of the cache with each executor, rather than have global locks.

Hope it helps,
~p

**Comment by adamnovak** [comment]
@pgrosu I don't quite parse your notation here, or what you mean by having the cache "travel". The current design is that each machine (which I think @arostamianfar is calling a "worker") has its own separate cache, shared among all the jobs on that machine.

What is *supposed* to be happening here is that job 2 on worker B should [record in the database that it is going to download the file and commit](https://github.com/DataBiosphere/toil/blob/d07f003a2847455c11d564fad7fdaf321c7ffc4b/src/toil/fileStores/cachingFileStore.py#L1421-L1429), and then [download the file](https://github.com/DataBiosphere/toil/blob/d07f003a2847455c11d564fad7fdaf321c7ffc4b/src/toil/fileStores/cachingFileStore.py#L1441). It shouldn't hold a database write lock while the download is ongoing (although maybe it somehow is holding a read lock?).

Job 3, meanwhile, should run the same `INSERT OR IGNORE...` and `INSERT... WHERE...` write transaction, see that the file is in the process of being downloaded by someone else, and go [here](https://github.com/DataBiosphere/toil/blob/d07f003a2847455c11d564fad7fdaf321c7ffc4b/src/toil/fileStores/cachingFileStore.py#L1278-L1284), where it basically cleans up anything orphaned and then immediately checks again to see if the file is ready yet. It shouldn't be holding any locks during this spin-and-poll process, but maybe it is polling too fast, taking the write lock for its conditional writes, and starving the actual downloader from being able to record that the download is complete?

@arostamianfar Is Job 3 or Job 2 the one that is timing out due to the database being locked? And is it timing out near the beginning of the download, or at the end of the download?

It sounds like Job 3 is probably timing out a the beginning, since you want to look for places where the downloader can hold a lock. It's also interesting that in your stack trace, at the polling code, it can't get a write lock, and then the cleanup can't get a read lock, suggesting it is being starved out by an exclusive writer lock held by somebody else. But, I don't see anywhere where the downloader is going to hold a write lock for an appreciable time, except maybe [here where it records files it deleted in a loop](https://github.com/DataBiosphere/toil/blob/d07f003a2847455c11d564fad7fdaf321c7ffc4b/src/toil/fileStores/cachingFileStore.py#L643-L648). Is it possible that there are multiple Job 3s all banging on the database as fast as they can, and one of them is getting starved out by the others polling (via conditional writes) much more often than they need to?

Things we could try:

1. Add a sleep to the loop that Job 3 is in, polling for the file to be ready.
2. Change [this loop](https://github.com/DataBiosphere/toil/blob/d07f003a2847455c11d564fad7fdaf321c7ffc4b/src/toil/fileStores/cachingFileStore.py#L643-L648) where we execute deletions to free up space to commit after we record each deletion, instead of all of them, in case a lot of files were deleted.
3. Change that loop to poll using reads if the downloading file is still there, instead of going back to the beginning and trying to take ownership of the download on the off chance that the download we saw before was orphaned and got cleaned up.
4. Wrap all our SQL in connection context managers to be super sure that we don't forget to commit.
5. Don't keep connections to the database open persistently, on the theory that they may keep read locks longer than they need to and thus stall writers.

**Comment by adamnovak** [comment]
OK, if I knock the timeout down to 5 seconds, and I run 30 simultaneous jobs trying to download the same file, and I add a delay to the download so it takes a long time, I can replicate this. It does look like some would-be writers are starving.

I will try to fix it.

**Comment by arostamianfar** [comment]
Thanks, Adam! One additional piece of data that can be useful: I realized that throughout my tests, the exception actually happens ~ at the same time as when a pending upload is done in another job (i.e. after the `commitThread` is done), which is kinda strange.
So, my setup is like:
* Job 1 is downloading a large file, `F`, from the jobstore into the cache.
* Job 2 is uploading another large file to the jobstore (inside `_executePendingUploads`)
* Job 3 is waiting on `F` to be downloaded (job 1 owns the download).

The exception actually happens in `job 3` once `job 2` is done.
I tried adding a 20second sleep in the loops, but the exception still happened.

**Comment by arostamianfar** [comment]
Interestingly, the same job fails again after retry (I used retryCount = 1), but it happens during init this time, which seems to suggest something is locking the db for a long time:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 357, in workerScript
    caching=not config.disableCaching)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/abstractFileStore.py", line 120, in createFileStore
    return fileStoreCls(jobStore, jobGraph, localTempDir, waitForPreviousCommit)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 243, in __init__
    self._ensureTables(self.con)
  File "/usr/local/lib/python2.7/dist-packages/toil/fileStores/cachingFileStore.py", line 281, in _ensureTables
    """)
OperationalError: database is locked
```

**Comment by pgrosu** [comment]
@adamnovak Thank you for the detailed description, which helped me quite a bit.  Basically what I am describing is the CQRS (Command Query Responsibility Segregation) pattern.  You would have two databases:

1) A database for creates, updates, and deletes (CUD).
2) A separate database for reads.  This is kept up-to-date via events coming via a publish-subscriber pattern from the (1) command-side database changes.

Each process on each worker on each machine gets a copy of the cache satisfying immutability.  On top of that consistency (from the CAP theorem) is satisfied via the 1st database.  You don't need `IGNORE` in any of the SQL statements, as those indicate inconsistencies of the design model.  A bit better is if you have a micro-service in front of database 1, that ensures consistency is preserved of orchestrated CUD events.  Then you encapsulate it the way you suggested in the last posts/PR via a retry-logic that will not proceed until it satisfies a precondition-contract ensuring a successful completion of the series of steps within or across workers.  This also has the added benefit allowing you to record-and-replay timestamped events from both databases to determine race conditions.

The logic I wrote is as follows in ordered set-form:

`Job_Number[ Worker_ID ]( Arguments ) :=` this means given a `Job_Number` on `Worker_ID` operates on `Arguments`.

Example: `Job_1[Worker_A](Cache_Copy_1) -> F` means it will produce file F, where the `->` represent a function with the left-side of the arrow representing the domain/input with the right the range/output of it.

Then you compose these functional units in a set of operations mapped from left-to-right, which I updated based on how you described it should run -- `database_record` can be thought of as a reactive message with completion-triggering the `download_file()` functional unit:

`Job_Definition_Worker_12 := Job_2[Worker_B](Job_1[Worker_A](Cache_Copy_1) -> F, Cache_Copy_2) -> { database_record( download_file_request, commit) -> download_file() }`

`Job_3[Worker_B](Job_Definition_Worker_12) -> cleanup_results()`

Hope it helps,
~p

**Comment by adamnovak** [comment]
@pgrosu So you're suggesting that the cache state tracking database (not the cache itself; we can't keep many copies of its large many-gigabyte files) be set up so that readers all have their own full read copies of the database, that they keep up to date themselves, and all the writing (things like "I have downloaded this file", or "I am deleting this cached file, so no more references to it may be created") is done by sending messages to some in-charge process, which updates its copy of the database if the command is accepted, or returns a failure if the command is in conflict with its view of the database, and then broadcasts out the actual accepted changes to all of the other processes so that they can update their copies. Kind of like a single-miner blockchain.

(We could also have a single reading copy of the state database, but then whatever writer is supposed to keep it up to date with the write copy would still contend with all the readers. Better than writer/writer contention, though, and it would save space and redundant copies of update messages.)

I still don't really understand your notation, and I can't find a good description of a "reactive message" or what it means to "completion trigger" a "functional unit". But I think we *could* implement this. On the other hand, it would require a bunch of primitives we don't have right now in Toil, such as network connections between the workers running on a node for passing messages over, a whole message-queueing system, a whole publish-subscribe system, and something to solve tricky problems of electing somebody to be the database write arbiter and replacing them when the job they are running under finishes or crashes. Some of these things might be nicely available as Python packages, but I don't see that we have a way to deploy a "real" message-brokering service like ZeroMQ, and we probably don't want to try to write one as part of Toil.
