### ISSUE TITLE
gridEngine support broken in 3.23.1

### ISSUE THREAD

**Issue by liinus** [DataBiosphere/toil#2952]
`cwltoil` does not redirect stdout and stderr to cwd when using `--batchSystem gridEngine`. This worked on 3.18.0 but is broken on 3.21.0 and 3.23.1 (tested using python2 only).

```
$ cwltoil --batchSystem gridEngine --logLevel DEBUG test.cwl data.yml
[...]
hostname 2020-02-04 12:23:44,659 Thread-41 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Running ['qsub', '-V', '-b', 'y', '-terse', '-j', 'y', '-cwd', '-N', 'toil_job_0', '-hard', '-l', u'vf=2097152K,h_vmem=2097152K', '-o', u'/tmp/toil-e18e756f-9eb2-4363-bbbb-2a3f899cf7e2-8b6f0bc66c81d2b9ef76a3fc9b52b452/toil_job_0_batch_gridengine_$JOB_ID_std_output.log', '-e', u'/tmp/toil-e18e756f-9eb2-4363-bbbb-2a3f899cf7e2-8b6f0bc66c81d2b9ef76a3fc9b52b452/toil_job_0_batch_gridengine_$JOB_ID_std_error.log', '_toil_worker file:///my/path/test.cwl file:/my/jobstore/path kind-file_my_path_test.cwl/instancet4Jqlz']
[...]
```

This brakes SGE support. Submitted jobs (e.g. toil_job_0) will fail because the tmp directory will not exist in /tmp on other hosts in the cluster.
```
$ qstat -j '716' | grep "error reason"
error reason          1:      02/04/2020 12:21:50 [1116:435]: error: can't open output file "/tmp/toil-cb1d45a1-1212-4937-9fbd-85de4b738c5e-8b6f0bc66c81d2b9ef76a3fc9b52b452/toil_job_0_batch_gridengine_716_std_output.log": No such file or directory
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-501)
┆Issue Number: TOIL-501

**Comment by liinus** [comment]
I suspect this is related to the new flag `--noStdOutErr`.

**Comment by liinus** [comment]
I think it's a problem redirecting stdout to workDir considering workDir should be a local directory (`/tmp` is the default): https://github.com/DataBiosphere/toil/commit/079e75705f542e4aa1722b4004e151ac084a7438

**Comment by kwwette** [comment]
`formatStdOutErrPath()` could check if `workflowDir` is accessible; if not it could fallback to `/tmp` for systems without a shared file system.

In the meantime, as a workaround you can use `--noStdOutErr` to send stdout and stderr to `/dev/null`, which will not try to access the `workflowDir`.

**Comment by liinus** [comment]
Thanks, my workaround was to patch it by disabling the redirect in gridengine.py. That works in my case because the cwd (where I run cwltoil) is a nfs share that's accessible by all worker nodes, an assumption I think can not always be made. The proper way to solve this might be to store the log files in the jobStore and to move it to the leader workDir on success/failure?

**Comment by adamnovak** [comment]
Is cwltoil issuing jobs that are just commands from the CWL workflow, and that don't go through `_toil_worker`? Because the standard output and error files for a job that runs the Toil worker will have more or less nothing in them, if the Toil worker manages to start up successfully. It redirects its output and error streams to files and puts them into the job store when it finishes or errors out, so that they can be spit out in the leader's log when it complains that a job has failed.

Without some kind of shim like that, and using just the various grid engines' output redirection facilities, I don't think there's a good way to get command output saved to an arbitrary Toil job store. In particular I don't think that SGE has a way to bring the log files from the worker back to the leader, and we'd need to rely on knowing a shared filesystem path somewhere.

That *isn't* what the workflow directory is supposed to be, AFAIK. I think it *always* has to be an accessible, writable directory on each worker, because it is where the worker will put its cache for downloaded files, and where it will make all the per-job temp directories. But there's no good reason to put it on a shared filesystem unless you don't have room in `/tmp` on each worker to run your jobs.

What's causing the problem here is that `getWorkflowDir()` produces node-specific directories *under* the workflow directory given by the user (to keep nodes' stuff separate if the user has specified a shared directory). So when you query it on one machine and then ship off a job to run on another machine and save its output there, it fails.

`formatStdOutErrPath()` IMHO should use whatever base directory the per-node workflow directories are being created under. Maybe `getWorkflowDir()` needs to be renamed to `getNodeWorkflowDir()` too.

**Comment by diekhans** [comment]
@liinus 
we have a PR that attempts to make the grid-engine like batch systems more robust and easier to debug.  However, we are unable to test them.  Would you be able to test it?

https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging
