### ISSUE TITLE
Similar index error when running cactus

### ISSUE THREAD

**Issue by ashlingcha** [DataBiosphere/toil#2957]
Hi there,
I'm getting a similar error to #2951 and am very unsure how to resolve this. I'm running on slurm and don't know why index is out of range. 

This is the command I use:
TOIL_SLURM_ARGS="--nodes 8 --time=4:00:00 --export=ALL" cactus --binariesMode local --batchSystem slurm --workDir=tmp --maxCores 28 --maxNodes 8 --defaultCores 28 --defaultDisk 96G --defaultMemory 96G jobStore2 $MYGROUP/cactus/examples/evolverMammals.txt $MYGROUP/cactus/examples/evolverMammals.hal

This is my error message:
Issued job 'mappingQualityRescoring' kind-mappingQualityRescoring/instancegygjLn with job batch system ID: 205 and cores: 28, disk: 96.0 G, and memory: 96.0 G
Issued job 'updateExpWrapperForOutgroups' kind-updateExpWrapperForOutgroups/instance82EDIl with job batch system ID: 206 and cores: 28, disk: 96.0 G, and memory: 96.0 G
Exception in thread Thread-281:
Traceback (most recent call last):
  File "/pawsey/sles12sp3/apps/gcc/4.8.5/python/2.7.14/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/group/pawsey0263/ashling_charles/software/sles12sp3/python/2.7.14/toil/git/lib/python2.7/site-packages/toil-3.23.1a1-py2.7.egg/toil/batchSystems/abstractGridEngineBatchSystem.py", line 235, in run
    activity |= self.checkOnJobs()
  File "/group/pawsey0263/ashling_charles/software/sles12sp3/python/2.7.14/toil/git/lib/python2.7/site-packages/toil-3.23.1a1-py2.7.egg/toil/batchSystems/abstractGridEngineBatchSystem.py", line 210, in checkOnJobs
    status = with_retries(self.getJobExitCode, batchJobID)
  File "/group/pawsey0263/ashling_charles/software/sles12sp3/python/2.7.14/toil/git/lib/python2.7/site-packages/toil-3.23.1a1-py2.7.egg/toil/batchSystems/abstractGridEngineBatchSystem.py", line 42, in with_retries
    return operation(*args, **kwargs)
  File "/group/pawsey0263/ashling_charles/software/sles12sp3/python/2.7.14/toil/git/lib/python2.7/site-packages/toil-3.23.1a1-py2.7.egg/toil/batchSystems/slurm.py", line 84, in getJobExitCode
    state, rc = self._getJobDetailsFromScontrol(slurmJobID)
  File "/group/pawsey0263/ashling_charles/software/sles12sp3/python/2.7.14/toil/git/lib/python2.7/site-packages/toil-3.23.1a1-py2.7.egg/toil/batchSystems/slurm.py", line 148, in _getJobDetailsFromScontrol
    job[bits[0]] = bits[1]
IndexError: list index out of range

Got message from job at time 02-06-2020 11:04:47: Input cigar file has 7362 lines
Got message from job at time 02-06-2020 11:04:47: Filtered, non-overlapping primary cigar file has 11273 lines
Got message from job at time 02-06-2020 11:04:47: Filtered, non-overlapping secondary cigar file has 31711 lines
Got message from job at time 02-06-2020 11:05:01: Input cigar file has 3872 lines
Got message from job at time 02-06-2020 11:05:01: Filtered, non-overlapping primary cigar file has 7942 lines
Got message from job at time 02-06-2020 11:05:01: Filtered, non-overlapping secondary cigar file has 16881 lines

I've tried looking through the files generated in the tmp directory but they are empty directories, and ive tried looking in the jobStore but I am confused as to where to be looking. 

Toil had been working as this is the 581th line of the error log and I had seen the toil jobs spawning on the queue. 
I also tried doing >out.txt 2>&1 as suggested in the other thread but got Submitted batch job 3644049 in the file

Thanks,
Ashling

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-504)
┆Issue Number: TOIL-504

**Comment by diekhans** [comment]
Does DEBUG logging record the response from the batch system commands?  If so, this would
be useful, otherwise a good thing to add..

**Comment by adamnovak** [comment]
No, I think it just always gets dumped straight into the parser and is never logged.

The relevant code is here; it looks like something is coming out of `scontrol` which is neither the one error message we try and parse, nor a `key=value` line. Possibly some sort of warning, or maybe just a dropped connection to the cluster.

https://github.com/DataBiosphere/toil/blob/dd5fde3aaf2fb25785baa00b3c96cf0b327c5588/src/toil/batchSystems/slurm.py#L126-L148

We ought to go through our CLI-based batch systems and change them to in general parse what they can and ignore the rest, instead of exploding as soon as they see anything they aren't expecting. We also should be logging our exchanges with the batch system at debug level, so we can debug things like this.

@ashlingcha I suspect your workflow might make progress if you `--restart` it.

**Comment by diekhans** [comment]
@ashlingcha 
we have a PR that attempts to make the grid-engine like batch systems more robust and easier to debug. However, we are unable to test them. Would you be able to test it?

https://github.com/DataBiosphere/toil/tree/issues/2951-slurm-logging

**Comment by ashlingcha** [comment]
Sorry I'm only running toil through a module loaded by the server of the hpc computers I am using, what kind of testing do you mean? should I get in contact with someone?

Thanks,
Ashling

**Comment by ashlingcha** [comment]
@adamnovak I'm trying to restart using this little script: 
```
cactus_args="--binariesMode local --batchSystem slurm --workDir=tmp2 --maxCores 24 --maxNodes 8 --defaultCores 24 --defaultDisk 96G --defaultMemory 96G jobStore2 /group/pawsey0263/ashling_charles/cactus/examples/pairwise.txt $MYGROUP/cactus/examples/out.hal"

TOIL_SLURM_ARGS="--nodes 8 --time=4:00:00 --account=pawsey0263 --export=ALL" 
cactus $cactus_args
while [ -d tmp2 ]
do
cactus $cactus_args --restart
done
```

but the TOIL_SLURM_ARGS dont seem to be passing through?

I Tried
```
cactus_args="--binariesMode local --batchSystem slurm --workDir=tmp2 --maxCores 24 --maxNodes 8 --defaultCores 24 --defaultDisk 96G --defaultMemory 96G jobStore2 /group/pawsey0263/ashling_charles/cactus/examples/pairwise.txt $MYGROUP/cactus/examples/out.hal"

TOIL_SLURM_ARGS="--nodes 8 --time=4:00:00 --account=pawsey0263 --export=ALL" cactus $cactus_args
while [ -d tmp2 ]
do
TOIL_SLURM_ARGS="--nodes 8 --time=4:00:00 --account=pawsey0263 --export=ALL" cactus $cactus_args --restart
done
```

but then the restart doesn't seem to work - any ideas of where I should be placing the TOIL_SLURM_ARGS?

**Comment by adamnovak** [comment]
It looks like in your first example you are setting `TOIL_SLURM_ARGS` as a shell variable, but not telling the shell to pass it on to programs you run. Try `export TOIL_SLURM_ARGS="whatever"`, so you don't have to put it on the same line as the command.

Your second version looks like the TOIL_SLURM_ARGS should have been passed through OK.

If your restart is producing the same sort of index errors you mentioned earlier, it would be useful for us if you could try the version of Toil that @diekhans posted. We've added more logging, so we should be able to get an error message out of it that includes exactly what Slurm is telling Toil in order to crash it. If you can't get it installed yourself, you could talk to the people who maintain your module and see if they can get it installed. It probably still won't *work*, but the error messages it reports should let us find and solve the underlying problem.

**Comment by diekhans** [comment]
changes in master should make HPC batches systems more robust.  Please reopen or file a new ticket if this is still a problem
