### ISSUE TITLE
Toil flags for cactus

### ISSUE THREAD

**Issue by ashlingcha** [DataBiosphere/toil#2961]
Hi there,
I get errors when running cactus on a slurm system - running on 6 nodes each with 24 cores which have 64G shared between the 24 cores for each node.

I had issues where I was running out of memory as one of the commands required 100M as shown here:
Issued job 'RunBlast' kind-RunBlast/instanceU4qn9L with job batch system ID: 155 and cores: 24, disk: 1.6 G, and memory: 100.0 M

I tried using the flag --maxMemory 60G in the full script TOIL_SLURM_ARGS="--nodes 6 --time=04:00:00 --qos=high --export=ALL" cactus --binariesMode local --batchSystem slurm --logDebug --workDir=tmp4 --maxCores 24 --maxNodes 6 --defaultCores 24 --maxMemory 60G jobStore4 evolverMammals.txt test.hal

but the memory is still being set for requesting 100M - any advice to get over this would be great.

Thanks,
Ashling

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-505)
┆Issue Number: TOIL-505

**Comment by adamnovak** [comment]
You might try `--defaultMemory` instead of or in addition to `--maxMemory`. The `--maxMemory` option is supposed to be an upper limit on the total memory the workflow will use at any given time; it doesn't influence how much memory each job requests, and I'm not sure it is actually implemented for the Slurm batch system. The `--defaultMemory` option sets how much memory each job will request if the workflow doesn't specify a memory request.

It's Cactus's responsibility to tell Toil how much memory each job needs, if it isn't going to use the default. So if `--defaultMemory` doesn't change the job's memory request, it is because Cactus is specifying something to override the default, and the Cactus bug tracker would be the place to figure out how to configure it.
