### ISSUE TITLE
Problems creating a simple non-dynamic workflow

### ISSUE THREAD

**Issue by rikardn** [DataBiosphere/toil#3009]
I am trying to create a simple workflow of one root job and one child job. The workflow should return the results of the child. I can do this using dynamic job creation, but since both jobs are well defined from the start I am trying to create a non-dynamic workflow. However I fail to do so 

Dynamic example that works:

```python
from toil.common import Toil
from toil.job import Job

toil_options = Job.Runner.getDefaultOptions("file:jobStore")
toil_options.clean = "always"

class ChildJob(Job):
    def run(self, file_store):
        return 43

class RootJob(Job):
    def run(self, file_store):
        return self.addChild(ChildJob()).rv()

if __name__ == '__main__':
    with Toil(toil_options) as workflow:
        root = RootJob()
        results = workflow.start(root)
        print(results)
```

My best effort non-dynamic workflow that fails with ```RuntimeError: Trying to pass a promise from a promising job that is not a predecessor of the job receiving the promise```

```python
from toil.common import Toil
from toil.job import Job

toil_options = Job.Runner.getDefaultOptions("file:jobStore")
toil_options.clean = "always"

class ChildJob(Job):
    def run(self, file_store):
        return 43

class RootJob(Job):
    def run(self, file_store):
        return self._rv

if __name__ == "__main__":
    with Toil(toil_options) as workflow:
        child = ChildJob()
        root = RootJob()
        rv = root.addChild(child).rv()
        root._rv = rv

        results = workflow.start(root)

        print(results)
```

Is it possible to create a workflow that returns the results of the child node that is not creating jobs dynamically? If not are there other ways of retrieving results of a child node?

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-526)
┆Issue Number: TOIL-526

**Comment by adamnovak** [comment]
This ought to work, I think. I can replicate that it doesn't.

It looks like the problem might be that shipping the promise to the job that also has the promising job as a child might result in the child job being pickled twice (once inside the promise and once as a child). When we pickle a job, it runs `__reduce__`, which throws out the `_promiseJobStore`:

https://github.com/DataBiosphere/toil/blob/2bd7920478779aa35b775da87f241a7377282e85/src/toil/job.py#L1141-L1150

The `_promiseJobStore` being empty is later used as a signal that we're mis-using promises and sending them places they can't be resolved:

https://github.com/DataBiosphere/toil/blob/2bd7920478779aa35b775da87f241a7377282e85/src/toil/job.py#L571-L574

I think we can probably put the job back to its old state after pickling and fix this, but I'm not sure if that will let that check for real mis-use of promises still work.

**Comment by adamnovak** [comment]
OK, when I hack around that, the unpickling logic complains, because the parent/root job contains a promise for the child job's return value, but the child job hasn't run yet. So even though the root job just wants to return the child job's return value promise, it cannot itself be loaded because Toil thinks we're mishandling promises if it unpickles one for something that hasn't happened yet.

**Comment by adamnovak** [comment]
Just passing the child job itself, instead of the promise, to the parent job doesn't do it either. It looks like the parent and child jobs actually work, but then when unpickling the return value of the root job in the leader, the promise is unresolved. It might have something to do with how promises are forwarded.

Unfortunately, I think to make this work, we would have to substantially revise Toil's promise system; right now it's pretty tightly coupled in terms of what a pickled promise vs. an actual value means, and it has strong ideas about what order things are supposed to be pickled and unpickled in that are violated if you don't create the promises or the child jobs within the jobs that actually have them as children.

As a workaround, I would advise:
1. Setting up a new root job above the one you have now that wires up the workflow.
2. Making *that* root job directly return a promise for the result of the (grand)child job you are interested in, instead of passing it up through the (current) root job.

Then you can still define your workflow structure all in one place, but Toil will be satisfied with the order in which your promises are created and pickled and unpickled. It's perfectly fine to work with and return promises for any descendants of your own job, not just direct children. You just can't pass promises to parents of the jobs that promise them, or pass whole jobs around as arguments to other jobs.

**Comment by rikardn** [comment]
Thanks @adamnovak for your ideas. Unfortunately I cannot get your workaround to work. I am testing the following code with the latest development version:

```python
from toil.common import Toil
from toil.job import Job

toil_options = Job.Runner.getDefaultOptions("file:jobStore")
toil_options.clean = "always"

class ChildJob(Job):
    def run(self, file_store):
        return 43

class RootJob(Job):
    def run(self, file_store):
        return 28

class GrandRootJob(Job):
    def run(self, file_store):
        return self._rv

if __name__ == "__main__":
    with Toil(toil_options) as workflow:
        child = ChildJob()
        root = RootJob()
        grand = GrandRootJob() 
       
        rv = root.addChild(child).rv()
        grand._rv = rv
        grand.addChild(root)

        results = workflow.start(grand)

        print(results)
```

It fails with the same error message. Did you mean something else?

**Comment by adamnovak** [comment]
Yeah, that's not quite what I meant. I think that the `if __name__ == "__main__":` block needs to just make `GrandRootJob`, and then `GrandRootJob` needs to wire things up, taking care not to send any parent jobs promises from their child jobs. Something like:

```
from toil.common import Toil
from toil.job import Job

toil_options = Job.Runner.getDefaultOptions("file:jobStore")
toil_options.clean = "always"

class ChildJob(Job):
    def run(self, file_store):
        return 43

class RootJob(Job):
    def run(self, file_store):
        return 28

class GrandRootJob(Job):
    def run(self, file_store):
        child = ChildJob()
        root = RootJob()
        rv = root.addChild(child).rv()
        self.addChild(root)
        return rv

if __name__ == "__main__":
    with Toil(toil_options) as workflow:
        grand = GrandRootJob() 
        results = workflow.start(grand)
        print(results)
```

Here we still manage to return the result of `ChildJob`, and the workflow structure is defined (almost) all in one place (inside `GrandRootJob`). Note that we don't give `ChildJob`'s result promise to `RootJob` for it to return back to us. We just pick it up when we are wiring up the workflow and return it back to the main script.

**Comment by rikardn** [comment]
Ah, I see. But isn't this again a dynamic creation of child jobs on the worker side as in my first example? 

If there are no big drawbacks of not creating the full workflow before sending it away I can live with this.

**Comment by adamnovak** [comment]
It does create jobs while the workflow is running. But it does it
still in a centralized location, so you don't have job creation
sprinkled throughout the entire workflow, with each job creating its
own children and follow-ons.

I don't think there are big drawbacks to creating the workflow as it
runs, other than the problems you can run into if you scatter the code
to do it across the whole file so you have no central overview of the
structure. Toil is designed to handle dynamically-generated workflows.

You can also still create the whole workflow before you start the root
job, but then you can't connect up jobs with promises (until we
redesign the promise system), because the promises would need to be
serialized and deserialized without being resolved. If you still have
to pass data around (e.g. from children of a job to follow-ons of that
job), you could use the writeSharedFileStream/readSharedFileStream
methods of the job store (which you can get from the file store) and
keep everything in predictably-named files:
https://toil.readthedocs.io/en/releases-3.23.1/developingWorkflows/toilAPIJobstore.html#toil.jobStores.abstractJobStore.AbstractJobStore.writeSharedFileStream

**Comment by rikardn** [comment]
Thanks @adamnovak for taking the time to explain. Now I know how to proceed.

**Comment by adamnovak** [comment]
It seems like this particular case is resolved. I'll open an issue about maybe making the promise system more flexible.
