### ISSUE TITLE
Cannot execute sample code snippet

### ISSUE THREAD

**Issue by vlakhujani** [DataBiosphere/toil#3049]
I am a beginner with Toil and I am trying to execute the below code snippet from [this](https://www.biorxiv.org/content/10.1101/062497v1.full.pdf) paper.

```
from toil.job import Job

def helloWorld(message, memory="2G", cores=2, disk="3G"):
	return("Hello, world!, here's a message: %s" % message)

j = Job.wrapFn(helloWorld, "you did it")

if __name__=="__main__":
	parser = Job.Runner.getDefaultArgumentParser()
	options = parser.parse_args()
	Job.Runner.startToil(j, options)
```
and then execute this as

```python
python HelloWorld.py file:jobStore
```

and it says:

```
bioinfo-pc 2020-05-02 15:48:27,718 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxCores to CPU count of system (16).
bioinfo-pc 2020-05-02 15:48:27,719 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxMemory to physically available memory (33393303552).
bioinfo-pc 2020-05-02 15:48:27,719 MainThread WARNING toil.batchSystems.singleMachine: Limiting maxDisk to physically available disk (61916790784).
bioinfo-pc 2020-05-02 15:48:27,754 MainThread INFO toil: Running Toil version 3.21.0-89670c051803f334af625f93d058f76e2bc17201.
bioinfo-pc 2020-05-02 15:48:27,764 MainThread INFO toil.leader: Issued job 'helloWorld' kind-helloWorld/instancedin_1tjk with job batch system ID: 0 and cores: 2, disk: 3.0 G, and memory: 2.0 G
INFO:toil.worker:Redirecting logging to /tmp/toil-29e36e98-fd86-4918-99b0-c2b1987fbfb4-fe9955c3028b4ff39ed9395fddb024af/tmp78er70s5/worker_log.txt
bioinfo-pc 2020-05-02 15:48:27,972 MainThread INFO toil.leader: Job ended: 'helloWorld' kind-helloWorld/instancedin_1tjk
bioinfo-pc 2020-05-02 15:48:29,785 MainThread INFO toil.leader: Finished toil run successfully.
bioinfo-pc 2020-05-02 15:48:29,809 MainThread INFO toil.common: Successfully deleted the job store: FileJobStore(/home/bioinfo/Desktop/toil_test/jobstore)

```

I am not sure why it is not printing 

`Hello, world!, here's a message: you did it`

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-545)
┆Issue Number: TOIL-545

**Comment by adamnovak** [comment]
You're missing the `print` from the last line of the sample code. Since that sample code is Python 2, you need to upgrade it to Python 3 by wrapping the argument to `print` in `()`, rather than by deleting the `print`. So the last line should be:

```
        print(Job.Runner.startToil(j, options))
```

Your job composes and returns the string, but when the string gets back to the main script (as the return value of `startToil()`, it is being discarded because you are not asking to print it. The return value of the root job isn't printed automatically.

I'm going to close this because I'm more or less certain that this should help. Please let me know if it doesn't and I'll reopen it.

**Comment by vlakhujani** [comment]
@adamnovak That solved the issue. Many thanks! :1st_place_medal:
