### ISSUE TITLE
Progress bar is cool but...

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#3069]
It requires the terminal to be `reset` when run in a screen session.  Also, for cactus anyway, it spends the vast majority of the runtime at 99%/100%.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-558)
┆Issue Number: TOIL-558

**Comment by adamnovak** [comment]
Te reset issue might be the same as https://github.com/Rockhopper-Technologies/enlighten/issues/16 which was closed for insufficient information. Maybe we can pick that back up.

The bar is going to spend most of its time almost done because it can only see the issued jobs. If we want it to use not-yet-ready-to-run jobs in the denominator we need an efficient way to get those from the job store, without walking the whole stored tree and with some notion of completed, deleted jobs, which I think we don't have.

**Comment by avylove** [comment]
@glennhickey, do you still see the issue with enlighten 1.5.2?

**Comment by glennhickey** [comment]
Upgrading to 1.5.2 does seem to fix it.  Thanks @avylove -- this seems like a simple patch for toil then..
