### ISSUE TITLE
Without workflow.restart() line, --restart flag deletes the jobstore instead of throwing an error.

### ISSUE THREAD

**Issue by Robin-Rounthwaite** [DataBiosphere/toil#3094]
I had accidentally been calling my workflow as follows:
```
with Toil(options) as workflow:
        if not workflow.options.restart:
            output = workflow.start(Job.wrapJobFn(my_function, options))
```
without including the restart option:
```
        else:
            output = workflow.restart()
```

When I ran the workflow from the command line using the --restart flag, I got the following uninformative response:
`
robin-Surface-Book 2020-06-23 12:31:55,950 MainThread INFO toil.common: Successfully deleted the job store: FileJobStore(/home/robin/paten_lab/cactus_projects/cactus_count_bases_unmapped/js)
`
It would be more useful if it threw an error instead.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-574)
┆Issue Number: TOIL-574

**Comment by adamnovak** [comment]
Actually, if you're not calling restart but not calling start either,
I think it probably should do nothing (instead of deciding it
succeeded and cleaning up the job store). I bet we're cleaning up the
job store when we don't observe a failed workflow run, rather than
when we do observe a successful one.
