### ISSUE TITLE
toil does not install boto3 and boto in prepare step for toil-cwl-runner

### ISSUE THREAD

**Issue by nikhil** [DataBiosphere/toil#3565]
After installing toil using:
```
make prepare
make develop extras=[cwl]
```
I get ModuleNotFoundErrors for boto and boto3 from toil-cwl-runner. Maybe boto should be added to cwl_reqs here: https://github.com/DataBiosphere/toil/blob/master/setup.py#L66

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-878)
┆Issue Number: TOIL-878

**Comment by DailyDreaming** [comment]
@nikhil Oof, will fix.  Thanks for reporting this!

**Comment by davidlougheed** [comment]
i also encounter this with the wdl runner

**Comment by longr** [comment]
Just been running into this error.  It looks like toil now needs `boto` and `boto3` in its core requirement due to a change in how `toil.aws.zone_to_region` works. This function is called from `common.py` and now calls a second function that tries to `import boto`.   Looks like this change was introduced in commit:  98dbf33147ed029800dd43a73ee5c64e83feda7b

https://github.com/DataBiosphere/toil/commit/98dbf33147ed029800dd43a73ee5c64e83feda7b#diff-4c03512d16483ff0799c14abf228b01b0c9bcce9e6b608dc4ed6b745c217ae4a

**Comment by davidlougheed** [comment]
It also may make sense to add this type of check to a CI test?
