### ISSUE TITLE
REST API to run CWL workflows on AWS with Toil

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3612]
Good Afternoon Everyone,

Apologies if this has been asked and answered. Our team is looking to leverage Toil to run our CWL pipelines in AWS and wanted a bit of guidance on if our design is possible. 

For context, all of our data lives on local HPC file systems, and we are **currently** using Airflow to run local CWL pipelines.

We are trying to run these CWL pipelines, through Toil, remotely on AWS. To use Toil for this, it seems that we would have to SSH onto the AWS cluster to initiate these pipelines. Is this a correct assumption, or are we able to initiate all of this remotely? Best case scenario for us would be the following:

- We transfer data to AWS (the input data)
- We have a Toil script written to accept the following: CWL pipeline file, CWL yml file, command line arguments
- Toil script moves this data to AWS
- Toil script runs the CWL pipeline on the pre-provisioned AWS cluster

If this is not clear - please let me know.

Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-898)
┆Issue Number: TOIL-898

**Comment by nikhil** [comment]
Hey @jpuerto-psc,

I would check out this section of the documentation: https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#running-a-cwl-workflow-on-aws. It seems to be exactly what you would need. You can remotely run and transfer data to AWS.

**Comment by jpuerto-psc** [comment]
@nikhil Thanks for that link! Not sure that would cut it though. Seems that you still need to ssh into the leader node and run the cwl pipeline locally on that machine:

![image](https://user-images.githubusercontent.com/68066250/118309663-95338e00-b4bb-11eb-986f-2f06cb53e5e5.png)

**Comment by nikhil** [comment]
@jpuerto-psc, ahh you are right. I see that their is an option for kubernates but not cwl: https://toil.readthedocs.io/en/latest/running/cloud/kubernetes.html#option-2-running-the-leader-outside-kubernetes
Not sure why there is not an option mentioned for cwl. I will let someone more knowledgable of aws+cwl answer.

**Comment by DailyDreaming** [comment]
Hi @jpuerto-psc , is this a kubernetes cluster on AWS?

We support two cluster types on AWS:
 - Mesos support with CWL on AWS is the current default and fully supported (which requires ssh and also ships files via rsync, which I believe also uses port 22).
 - Kubernetes support with CWL on AWS is currently undergoing work to meet all of the conformance test requirements right now and is in a beta stage.  We're in the process of transitioning to kubernetes as the new default.

How do you want to remotely access the cluster?  If port 22 is not open, which ports are available?  We've thought about streamlining the run command to a one-liner so that the user doesn't see or have to deal with the ssh/rsync interactions, but that would still need those ports to be open.

We also, alternatively, may have a protoype server with an API to post workflow runs in the pipes, but that's some months off from being in Toil proper.

**Comment by jpuerto-psc** [comment]
@DailyDreaming Not a Kubernetes cluster - just the default.

Would something along these lines be what you are referring to:

`toil-ssh --zone us-west-2a <cluster-name> --command '<file_path_to_toil_cwl_runner_bin> <toil_cwl_commands>' `

I am fine with using port 22 - I just want to avoid having to **actually** having to SSH in. I am not concerned about the data movement as we have a solution for that. Just being able to initiate the workflow without having to ssh in is what we are looking for.

What would be the "ultimate" solution would be for a more integrated approach to handling CWL workflows from within the Toil API. Being able to kick this all off, from a Toil script on our HPC cluster, would be ideal. We would just pass in the appropriate cluster information and the CWL pipeline details (CWL file, YML file, and any additional command-line args) without having to worry about using subprocess directly.

I imagine what you all are looking at with the prototype server is some sort of REST API for calls back and forth?

**Comment by DailyDreaming** [comment]
@jpuerto-psc Yes, the prototype server would simply be a REST API.  Toil has a branch (untested) with the WES endpoints documented here: https://editor.swagger.io/?url=https://ga4gh.github.io/workflow-execution-service-schemas/openapi.yaml  The work would be testing and evaluating the server.

And yes, that command is exactly the kind of thing that Toil could use I think.  I think it would be straight forward to implement, though work on the server and creating a config file so that someone could simply kick it off easily would be ideal.  We just haven't had time to do this with our other priorities lately, unfortunately.

**Comment by DailyDreaming** [comment]
I imagine we'll get to this sometime in the next few months, but we also welcome any outside contributions as well if this is something you wish to implement.  Adam and I would be more than willing to spend time reviewing and helping with this if so.

**Comment by jpuerto-psc** [comment]
@DailyDreaming We are definitely interested in using this REST API for production level running. I don't think that the SSH bash script I've written will cut it unfortunately. Please let me know how I can help with moving this forward.

Best,

Juan

**Comment by adamnovak** [comment]
I think `toil ssh-cluster` might already take a command to run like `ssh` does.

**Comment by adamnovak** [comment]
Yes, we already collect all the extra command line arguments:
https://github.com/DataBiosphere/toil/blob/88db778b3917de4c92e5749c1072ae4ea3da1eea/src/toil/utils/toilSshCluster.py#L35
And we replace our default command of "bash" if they are specified:
https://github.com/DataBiosphere/toil/blob/88db778b3917de4c92e5749c1072ae4ea3da1eea/src/toil/utils/toilSshCluster.py#L48

So that should be a workaround for now, until we get the actual REST API server going.

**Comment by jpuerto-psc** [comment]
@adamnovak - yes this is what I am currently using. Still happy to offer our time to help get the REST API production ready.

Best,

Juan

**Comment by adamnovak** [comment]
@w-gao is in charge of the REST API server right now

**Comment by jpuerto-psc** [comment]
@adamnovak fantastic! Please let me know if there's anything I can do to help out with testing this out!

**Comment by mr-c** [comment]
@jpuerto-psc Great! @w-gao has asked for feedback about https://github.com/DataBiosphere/toil/pull/3779
