### ISSUE TITLE
AWS Cluster - Mount EFS

### ISSUE THREAD

**Issue by jpuerto-psc** [DataBiosphere/toil#3627]
Good Afternoon All,

Writing here to see if anyone has tried to mount EFS onto the Toil leader node? Seem to be having issues with this.

Best,

Juan

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-909)
┆Issue Number: TOIL-909

**Comment by adamnovak** [comment]
Hello @jpuerto-psc!

Sorry to hear that you are having trouble mounting EFS.

I think you can go into the AWS console and manipulate the leader instance from there to get EFS mounted on it, assuming that the AMI we use (Flatcar) is compatible? But that will only get it mounted into the Flatcar Container Linux environment (where you get to if you `ssh core@<IP>`). The Toil appliance (where you go if you `toil ssh-cluster`) won't see the mountpoint because it won't be mounted into the container.

To see it in the container, you could bind mount it over to inside of something the Toil leader container can get to already, in its [list of mounts](https://github.com/DataBiosphere/toil/blob/09ff43e553b4917b3ff37a4e637717fdfbf703f3/src/toil/provisioners/abstractProvisioner.py#L711-L719), or you can find the `toil-leader.service` systemd unit in the Flatcar environment and edit it to add another mount for EFS, and then restart.

If we actually wanted to have this as a Toil feature, we'd need something to control it in `toil launch-cluster` (maybe a command line option?), some kind of method on the `AbstractProvisioner` to tell it to mount a cloud-specific filesystem, with the details of what to mount, some code in the AWS provisioner to make sure to attach the EFS volume when requested, and then some logic in the AbstractProvisioner to expose the mount from the host into the Toil container.

**Comment by jpuerto-psc** [comment]
@adamnovak Thanks for the advice here! I figured that this might be the case. We went ahead and moved forward with using S3 buckets instead, since they seem to be more widely supported currently in Toil (rather than the EFS work around).

Thanks again!

Best,

Juan
