### ISSUE TITLE
require PRs to format new/changed code with black

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3685]
This is easily automated with https://github.com/akaihola/darker

Example to format: `darker --revision origin/master src/`

Instructions as a pre-commit hook: https://github.com/akaihola/darker#using-as-a-pre-commit-hook

Method to verify as part of CI linting: `darker --check --revision origin/master src/`

Can also add in import sorting with the `--isort` option.

If @DailyDreaming @adamnovak approve, then I can send in a PR to implement this in CI, document this, and add a new target to the Makefile.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-943)
┆Issue Number: TOIL-943

**Comment by adamnovak** [comment]
How much time do you think we are are we wasting as a result of our code not following Black's style? How does that compare to the amount of time we would need to spend to implement and follow this new policy?

If we decide we do want to adopt Black's style, is there a good reason to use Darker to apply it just to new/changed code, instead of using Black to apply it to the whole codebase? With the variable snake_case_ification and the type hints, there's not (that I know of) a good automated way to do it, so we're applying the policy to new code and not insisting people completely redo everything in the first PR. But Black could be run once to fix up the whole codebase at once, right?

And if Black can just run and fix the code, is there a reason to structure the formatting policy as a check that can fail rather than a fix that can be automatically (maybe periodically) applied?

**Comment by mr-c** [comment]
I'm happy for black to be run on the whole codebase at once (and that would be my preference). But if a incremental approach is desired then here is a way to do it.

**Comment by adamnovak** [comment]
I'm going to close this since I think the PR #4348 that just does everything and fixes the git-ignore makes more sense.
