### ISSUE TITLE
cannot import name 'convert_pathsep_to_unix' from 'cwltool.utils'

### ISSUE THREAD

**Issue by caballero** [DataBiosphere/toil#3736]
Hi, I did a fresh install of toil 5.4.0 using pip, but trying to use it raised this error:

```
(toil-5.4.0) bash-4.4$ toil-cwl-runner --debug  --singularity long_read_assembly.cwl long_read_assembly_noHost.yml
Traceback (most recent call last):
  File "/hps/software/miniconda3_py3.9/envs/toil-5.4.0/bin/toil-cwl-runner", line 5, in <module>
    from toil.cwl.cwltoil import main
  File "/hps/software/miniconda3_py3.9/envs/toil-5.4.0/lib/python3.9/site-packages/toil/cwl/cwltoil.py", line 78, in <module>
    from cwltool.utils import (
ImportError: cannot import name 'convert_pathsep_to_unix' from 'cwltool.utils' (/hps/software/miniconda3_py3.9/envs/toil-5.4.0/lib/python3.9/site-packages/cwltool/utils.py)

```
Checking the file (utils.py) that method is missing.

I tried installing a previous version I used before (toil 5.2.0) in a separate environment but got the same error.

┆Issue is synchronized with this [Jiraserver Task](https://ucsc-cgl.atlassian.net/browse/TOIL-983)
┆Issue Number: TOIL-983

**Comment by adamnovak** [comment]
Hello @caballero. Sorry to hear you are having trouble with this.

Did you install `toil[cwl]` with `pip`, or just `toil`? If you don't tell `pip` that you need the `cwl` extra, then it won't install `cwltool` (because some Toil users don't need it). But if you already have `cwltool` installed, and it's the wrong version for Toil, then `toil-cwl-runner` can start and crash.

If you `pip install --upgrade toil[cwl]==5.4.0`, does it continue to crash? And if so, what versions do you have for `cwltool` and `toil` in `pip list`?

**Comment by caballero** [comment]
Hi @adamnovak, my bad, I thought the "pip install toil" will grab the toil[cwl] dependency. I just installed it and now it is working, I'm closing this ticket
