### ISSUE TITLE
docker/Dockerfile.py contains errror in arm check ; not under test?

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3952]
Credit to @mhpopescu 

https://github.com/DataBiosphere/toil/blob/b084951c38b00e7457a0a80073229748c6114233/docker/Dockerfile.py#L144

`[$TARGETARCH = amd64]` should be `[ $TARGETARCH = amd64 ]`; otherwise the test always fails and the arm64 route is always picked

As for testing, [`py36_appliance_build`](https://github.com/DataBiosphere/toil/blob/master/.gitlab-ci.yml#L108) calls `make push_docker` which does call `docker/Dockerfile.py` but the result is not checked

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1105)
┆friendlyId: TOIL-1105

**Comment by mr-c** [comment]
Proof:

```
docker pull quay.io/ucsc_cgl/toil:5.6.0a1-b084951c38b00e7457a0a80073229748c6114233-py3.6
$ docker run quay.io/ucsc_cgl/toil:5.6.0a1-b084951c38b00e7457a0a80073229748c6114233-py3.6 /usr/local/bin/docker
standard_init_linux.go:228: exec user process caused: exec format error
```

Which can be turned into a test

**Comment by adamnovak** [comment]
So the net result of this is that we ship an ARM `docker` binary in the Toil appliance, which will cause trouble for anyone using Docker-in-Docker to e.g. run CWL workflows, right? And we never catch it because we run the CWL conformance tests (and all our CWL tests) either single-machine in our Kubernetes-based Gitlab runners, or against our Kubernetes cluster, and those all make CWL use Singularity. And when we run stuff on Mesos clusters, if we ever use Docker, we do it as sibling containers via a connection to the host daemon that gets mounted in, and the Python API.

Maybe the right test here is to add invoking the Docker binary to the Dockerfile step that adds it? Or will that just always pass because to even do the ARM builds we set up `binfmt-misc`?
