### ISSUE TITLE
CWL: Implement the new cwltool:CUDARequirement resource requirement

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3982]
https://github.com/common-workflow-language/cwltool/pull/1581

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1114)
┆friendlyId: TOIL-1114

**Comment by adamnovak** [comment]
@mr-c How are `CUDARequirement` and `DockerRequirement` supposed to interact?

It looks like `cwltool` checks to see if `nvidia-smi` exists in its container, and if not it decides it can't do anything CUDA related. But if `cwltool` itself is running in one container, and the workflow specifies that the CUDA workload should be run in a different container, you *shouldn't* actually need `nvidia-smi` in the container with cwltool, right?

The `--gpus` option [is now part of stock Docker](https://github.com/docker/cli/issues/2063), and so you should be able to use a stock `docker` client from an environment without any nvidia tools to launch a container on a Docker daemon that [has the `nvidia-container-runtime` installed](https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/tree/main/cmd/nvidia-container-runtime), as long as the Docker *daemon* has access to the nvidia tools.

For Singularity, [it looks like you need the nvidia utilities accessible](https://sylabs.io/2021/10/nvidia-gpu-support-in-singularityce-3-9/) to use its [`--nv` option](https://drdaved-singularity-userdocs.readthedocs.io/en/latest/gpu.html#requirements).

Anyway, since at least in some environments, Toil wants to run cwltool in a Toil container that we need to redistribute, while the Docker containers it launches will often run against the host Docker, it would be useful if `cwltool` could support the case where it can't use any CUDA utilities but the backing Docker host can.
