### ISSUE TITLE
EOFError when reading job file from a failed job using fileJobStore

### ISSUE THREAD

**Issue by jsmedmar** [DataBiosphere/toil#3998]
Best regards, I'm using Toil 3.19.0. When deploying a pipeline using preemptible machines, I think the `job` file is not being written properly and Toil fails:

```python
WARNING:Job failed with exit value 1: 'testjob' __rsrceyJydW50aW1lIjogIjQwMDAwIn0=rsrc__ G/T/jobGPqFIR

Traceback (most recent call last):
    ContainerJob.Runner.startToil(head, options)
  File "/efs/local/toil/src/toil/job.py", line 786, in startToil
    return toil.start(job)
  File "/efs/local/toil/src/toil/common.py", line 771, in start
    return self._runMainLoop(rootJobGraph)
  File "/efs/local/toil/src/toil/common.py", line 1044, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/efs/local/toil/src/toil/leader.py", line 211, in run
    self.innerLoop()
  File "/efs/local/toil/src/toil/leader.py", line 542, in innerLoop
    self._gatherUpdatedJobs(updatedJobTuple)
  File "/efs/local/toil/src/toil/leader.py", line 499, in _gatherUpdatedJobs
    self.processFinishedJob(jobID, result, wallTime=wallTime)
  File "/efs/local/toil/src/toil/leader.py", line 772, in processFinishedJob
    jobGraph = self.jobStore.load(jobStoreID)
  File "/efs/local/toil/src/toil/jobStores/fileJobStore.py", line 198, in load
    job = pickle.load(fileHandle)
EOFError
```

The problem is that given the nature of the `.jobStore.load()` implementation, I would not know how to recover from such a situation. If the job can't be unpickled, how can I reduce its retry count? How can I ensure that it's rerun again?

Any help would be appreciated, unfortunately at the moment I cannot upgrade to a more recent version of Toil, and even if I could, I look into the code of the latest version and the problem would persist.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1125)
┆friendlyId: TOIL-1125

**Comment by jsmedmar** [comment]
This is the tree of the job directory:

```
$ tree jobstore/tmp/G/T/jobGPqFIR/

jobstore/tmp/G/T/jobGPqFIR/
|-- g
`-- job
```

**Comment by adamnovak** [comment]
If the job actually finished successfully, or if you don't care about the job completing but want to continue the workflow as best you can anyway, deleting the `job` file will make Toil think the job is done and move on to whatever else exists in the workflow.

If the job promised data to other jobs, the data won't be there, and those other jobs will fail.

What you really want to do is rerun the job. Unfortunately, if the data in `job` has been lost, due to a rename not being atomic, the job can't be rerun, and its connections to child and follow-on jobs for scheduling are also gone. You'd either have to have a `CheckpointJob` above the broken job in the tree to resume from, or you'd have to restart the workflow from the beginning. Or you could try and reconstruct the pickled object in the `job` file, based on a similar one, if you know what-all it ought to point at (maybe from the logs?), but that's almost certainly not worth your time to attempt.

The file job store really does depend on "proper" POSIX filesystem semantics (atomic rename and so on) for its correctness. If you are running on AWS with preemptable instances, is there a good reason you aren't using the `AWSJobStore`? It's designed for that environment.

If you really need to stop this happening, you can patch your `FileJobStore` to deal with your particular filesystem, as long as you can get it out to the workers. Maybe you could make sure to save a backup of the `job` file before replacing it, and add code to restore from the backup if the main file can't be read.

**Comment by adamnovak** [comment]
> if the data in job has been lost, due to a rename not being atomic, the job can't be rerun
This isn't *quite* true right now; I don't remember what it was like in 3.19. Now the job file holds just the scheduling info, including a `command` to run. That command *usually* links to a job body in a different file, which has the actual job code.

You could try figuring out which file (`g`?) the job body for this job is, and then unpickle it and run it from a custom script or hacked up version of the Toil worker. But making it happy to run would, again, probably not be worth your time.

**Comment by jsmedmar** [comment]
Thanks so much Adam for the quick response. In order to prevent this from happening again I've taken the following measure in my local copy of Toil (basically I just write the job data twice and try to read from the backup as a last resource). A bit of a hack but it will work for my use case. If someone in the future stumbles upon a similar issue, I looked and this same logic can be applied to the current version (using `update_job` and `load_job` instead). Thanks again Adam! Will close now.

```python
# fileJobStore.py
    ...
    
    def update(self, job):
        # The job is serialised to a file suffixed by ".new"
        # The file is then moved to its correct path.
        # Atomicity guarantees use the fact the underlying file systems "move" function is atomic.
        src = self._getJobFileName(job.jobStoreID) + ".new"
        dst = self._getJobFileName(job.jobStoreID)

        # Juan M. 01/11/22 keep a backup in case the `job` file gets corrupted
        # by leaving a backup we can recover from zero size job files
        backup = self._getJobFileName(job.jobStoreID) + ".backup"

        with open(src, 'wb') as f_1, open(backup, 'wb') as f_2:
            pickle.dump(job, f_1)
            pickle.dump(job, f_2)

        # This should be atomic for the file system, unless the filesystem crashes
        os.rename(src, dst)
        
    ...
    
    def load(self, jobStoreID):
        self._checkJobStoreId(jobStoreID)
        # Load a valid version of the job
        jobFile = self._getJobFileName(jobStoreID)

        # Juan M. 01/11/22, its possible that the jobFile is corrupted
        # in this case try reading the .backup file
        try:
            with open(jobFile, 'rb') as fileHandle:
                job = pickle.load(fileHandle)
        except EOFError:
            try:
                with open(jobFile + ".backup", 'rb') as fileHandle:
                    logger.warn("Recovering job from backup: %s", jobStoreID)
                    job = pickle.load(fileHandle)
                    self.update(job)
            except IOError:
                raise EOFError

        # The following cleans up any issues resulting from the failure of the
        # job during writing by the batch system.
        if os.path.isfile(jobFile + ".new"):
            logger.warn("There was a .new file for the job: %s", jobStoreID)
            os.remove(jobFile + ".new")
            job.setupJobAfterFailure(self.config)
        return job
```
