### ISSUE TITLE
iam.py error due to Boto3 not returning the type it claims to return from get_policy_version

### ISSUE THREAD

**Issue by larryns** [DataBiosphere/toil#4323]
Unless I'm mistaken, in the [iam.py](https://github.com/DataBiosphere/toil/blob/master/src/toil/lib/aws/iam.py) line 162 should be ```policy_document = policy_ver['PolicyVersion']['Document']``` without the ```json.loads()``` function call. I'm using the latest release of toil (5.8.0). Can someone please confirm?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1265)
┆Issue Number: TOIL-1265

**Comment by adamnovak** [comment]
This looks a lot like #4238; @Hexotical was going to make that change but decided against it.

The underlying web API [returns a URL-encoded JSON string for the policy document](https://docs.aws.amazon.com/IAM/latest/APIReference/API_PolicyVersion.html).

The AWS CLI tools [parse the JSON and output a single JSON document for the policy version without an embedded string](https://docs.aws.amazon.com/cli/latest/reference/iam/get-policy-version.html#examples).

The Boto3 API docs [claim that Document is a string](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.get_policy_version), but those are all auto-generated from Amazon's internal idea of what the API is and so those docs don't *always* reflect the actual behavior of the module when installed. If [this StackOverflow answer](https://stackoverflow.com/a/43106644) is accurate, the `Document` is actually presented as pre-parsed JSON in the Python API, and needs to be `json.dumps`'d before it can be printed in JSON format.

Also, boto3 has some open issues such as https://github.com/boto/boto3/issues/229 and https://github.com/boto/boto3/issues/978, and some de-facto rejected PRs like https://github.com/boto/botocore/pull/1154, around the problem that in a number of places where the API docs say the return type of something is a string, what is actually returned is a pre-decoded dict. The library apparently does this decoding because the decoded value is much more useful to the programmer.

But the documentation has never been updated to reflect this. It looks like this might be because [one part of Amazon is responsible for writing the documentation and a different part is responsible for writing the Python code](https://github.com/boto/boto3/issues/2918#issuecomment-876718124), and nobody actually feels like changing the documentation to match the behavior.

So as far as I can tell we should indeed drop the `json.loads` call, and if that results in type checking errors, that's a bug in the boto3 type stubs (which get generated from the same web API typing info as is used to generate the incorrect documentation), and [should be reported here](https://github.com/youtype/mypy_boto3_builder/issues), with a cast or type ignore comment in the code until the stubs are fixed.

@Hexotical Why did you decide not to make the change?

**Comment by larryns** [comment]
Thanks for the explanation @adamnovak. FYI, I was getting an error (stack trace) and when I removed the ```json.loads```, the error went away.
