### ISSUE TITLE
no root volumes in AWS workers

### ISSUE THREAD

**Issue by larryns** [DataBiosphere/toil#4324]
I'm trying to run the cactus example in a toil cluster on aws. My cactus run command is: 
```cactus --nodeTypes m6a.8xlarge,m5.8xlarge --minNodes 0,0 --maxNodes 20,2 --consCores 4 --provisioner aws --batchSystem mesos --metrics aws:us-east-1:cactus-examples --logDebug --logFile cactuslogs.txt evolverMammals.txt output.hal```. 

I'm using toil 5.8.0 with the default docker image (5.8.0 py3.9). My worker nodes are going from pending to terminated, and as far as I can tell the workers have no root volumes. So I assume that either no volumes are being created or attached; or the volumes are being detached right away. 

Any idea why this is happening?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1266)
┆Issue Number: TOIL-1266

**Comment by adamnovak** [comment]
I have seen nodes go straight to terminated before, as a cause of intermittent failures in the CI tests. I've never been able to figure out why, on account of not being able to catch them in the console.

Are you getting this *reliably*? Or does this only happen to some of the nodes?

It looks like when we use the AWS provisioner, [we make the root volumes for the new nodes with `delete_on_termination=true`](https://github.com/DataBiosphere/toil/blob/67d30afbe2693fd415cb01ebd080300f3eeeaecc/src/toil/provisioners/aws/awsProvisioner.py#L1052). So it could be that the volumes are being deleted on the AWS side when the termination happens and that's why you don't see them in the console when looking at the terminated nodes?

If you run your command with `--logDebug` and post the log, then we would get [the output from here where we log the volumes we are trying to make](https://github.com/DataBiosphere/toil/blob/67d30afbe2693fd415cb01ebd080300f3eeeaecc/src/toil/provisioners/aws/awsProvisioner.py#L1061), which would show if we are really asking for a node with no root volume somehow.

A workaround here might be to launch the cluster with [static provisioning](https://toil.readthedocs.io/en/latest/running/cloud/amazon.html#static-provisioning) so it at least always has a couple workers. You can use dynamic provisioning on top of that to let the workflow add additional nodes. And it might be easier to debug `toil launch-cluster` alone than `toil launch-cluster` and then the autoscaling workflow together; they should use the same code to create and destroy nodes.

**Comment by larryns** [comment]
Thanks for the quick response and suggestion @adamnovak. Let me do a little more digging and I'll get back to you as soon as I can.

**Comment by larryns** [comment]
So, I found and fixed the problem. It turns out that the root volume was being encrypted and didn't have kms iam permissions. Thanks for your help.
