### ISSUE TITLE
Make patch release to solve schema-salad issue

### ISSUE THREAD

**Issue by gmloose** [DataBiosphere/toil#4360]
When install installing Toil through `pip`, version 5.8.0 gets installed. This version pulls in a `schema-salad` version `8.3.x`, which is incompatible with Toil. To fix this, I (as a user) now need to manually upgrade `schema-salad` to version `8.4.20230201194352` or later. This is tedious and unnecessary. Fix is to make a patch release of Toil that pulls in the correct version of `schema-salad`. See https://gitter.im/bd2k-genomics-toil/Lobby?at=63d7f912ec2bfc62867d36e6 for reference.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1282)
┆Issue Number: TOIL-1282

**Comment by mr-c** [comment]
@adamnovak Shall I make a releases_5.8.1 branch that allows the newer version of schema-salad?

**Comment by adamnovak** [comment]
If `schema-salad` isn't going to yank the release with the bug or backport the fix to 8.3, I think we might need to make a release of Toil to fix this, and allow either newer versions or ban the broken ones that caused #4340.

I might make the release pinning an exact particular known good `schema-salad` version, because if we just depend on 8.4 it's going to be possible for the final release in the 8.4 series to break Toil in just the same way.

@DailyDreaming we can just follow https://github.com/DataBiosphere/toil/wiki/Toil-Release-Instructions right?

**Comment by adamnovak** [comment]
Until then I think using `schema_salad==8.3.20221028160159` will both make Toil 8.3 work and satisfy its official dependency requirements.

**Comment by mr-c** [comment]
@adamnovak That particular bug about pickling now has a specific and general test, so hopefully there won't be further breakage in schema-salad.

Schema-salad isn't set up for backports, no

**Comment by mr-c** [comment]
https://github.com/DataBiosphere/toil/releases/tag/releases/5.9.0 was released with this fix; thank you @DailyDreaming !
