### ISSUE TITLE
S3 Not use TMPDIR for S3 Downloads, use directly Jobstore

### ISSUE THREAD

**Issue by Guigzai** [DataBiosphere/toil#5024]
Hello,

TOIL Version 6.1
Python 3.9

We use S3 URIs as inputs to our workflows.

The leader toil uploads the files to the TMPDIR and then moves them to the JOBSTORE.
At the end of execution, it leaves them in the TMPDIR.

Why not upload them directly to the Jobstore ?

Thanks

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1618)
┆Issue Number: TOIL-1618

**Comment by stxue1** [comment]
@Guigzai Hey, thanks for the issue.

I've been trying to replicate this and need a bit more information. What type of jobstore are you setting for your workflow and are you running CWL, WDL, or using Toil in Python?

Additionally, can you provide an example reproducing this problem? I've attempted using an S3 input in Python, WDL, and CWL, and I haven't seen any leftovers in TMPDIR. I've tested with Toil 6.1.0 and 7.1.0a.

**Comment by Anael09** [comment]
Hi @stxue1, I am working with @Guigzai on this.
First of all thanks for your effort to replicate!

We are using a POSIX jobstore and CWL and here is an example that hopefully will help you: 
[test.zip](https://github.com/user-attachments/files/16835177/test.zip)

export AWS_PROFILE=testCWL
export AWS_CONFIG_FILE=s3_config
export AWS_SHARED_CREDENTIALS_FILE=s3_credentials
export TOIL_S3_HOST=my.s3.fr
export TOIL_S3_USE_SSL=True
export TOIL_S3_PORT=443
export TOIL_SLURM_ARGS="--account=my_slurm_account"
**export TMPDIR=/path/to/testToil/tmp**

mkdir -p ${TMPDIR}

toil-cwl-runner --batchSystem slurm --jobStore /path/to/testToil/jobstore1 --outdir /path/to/testToil/outdir1 --retryCount=0 --logInfo --disableProgress test.cwl args.json

With the CWL and args.json that you can find attached.

And at the end of the execution:

**du -hs /path/to/testToil/tmp/***
512	/path/to/testToil/tmp/tmp8t7e1y8_
1,0K	/path/to/testToil/tmp/tmpfdxfyz07
1,0K	/path/to/testToil/tmp/tmplpdnoqn2
1,8G	/path/to/testToil/tmp/tmpyxgybnw5  <======== this is the S3 file 
512	/path/to/testToil/tmp/toil_904129bb-f426-497a-9558-7d859286d7e1.1.20291152.err.log
8,0K	/path/to/testToil/tmp/toil_904129bb-f426-497a-9558-7d859286d7e1.1.20291152.out.log

**Comment by stxue1** [comment]
@Anael09 Hey, thanks for providing an example!

I've attempted to run it but I still don't seem to be able to replicate this behavior. My TMP directory remains empty except for log files throughout the entire CWL run, even when I provide a large file. I ran Toil 6.1.0 and 7.1.0a on Slurm and single machine with Python 3.10, and Toil 6.1.0 and 7.1.0 on single machine with Python 3.9. I've polled the TMP directory throughout a large file download and the TMP directory never appears to show anything. Instead, the jobstore directory grows by itself as the files seem to be downloaded directly.

https://github.com/DataBiosphere/toil/blame/8a8fed427cb46ab5cc78db11ad34d6d34d9e1817/src/toil/jobStores/aws/jobStore.py#L580
We [depend on boto3](https://github.com/DataBiosphere/toil/blob/8a8fed427cb46ab5cc78db11ad34d6d34d9e1817/src/toil/jobStores/aws/jobStore.py#L580) to do the [S3 download](https://github.com/boto/s3transfer/blob/da68b50bb5a6b0c342ad0d87f9b1f80ab81dffce/s3transfer/manager.py#L339-L385), and from poking around the source code, it'll do some type of [multipart download in chunks](https://github.com/boto/s3transfer/blob/da68b50bb5a6b0c342ad0d87f9b1f80ab81dffce/s3transfer/download.py#L365-L388) directly to the [FileIO stream we pass in](https://github.com/DataBiosphere/toil/blob/8a8fed427cb46ab5cc78db11ad34d6d34d9e1817/src/toil/jobStores/abstractJobStore.py#L482).

Does this TMPDIR leftover behavior happen only with big files or does it also happen with small files. Also, could you try to run the workflow on your end, with `args.json` with some s3 object such the below (either with a large or small file depending on when the issue happens, the below is about 2MB) and give us the debug logs?
```json
{"my_input_file":{"location":"s3://toil-datasets/wdl_templates.zip","class":"File"}}
```
The command should remain the same, except it should have `--logDebug` instead of `--logInfo`. I'd like to see if the suspected streaming behavior I'm seeing is not happening on your end.

**Comment by Anael09** [comment]
Thanks for your answer @stxue1!

I tried with a small 23 kB file and the behavior is still the same at the end of the execution:

du -hs /path/to/testToil/tmp/*
1,0K	/path/to/testToil/tmp/tmp71hku6eq
1,0K	/path/to/testToil/tmp/tmpa0tvs07m
512	        /path/to/testToil/tmp/tmpn1n6145p
**24K**	        /path/to/testToil/tmp/tmpuigei5ia **<======== this is the small S3 file**
512	        /path/to/testToil/tmp/toil_2d089094-e812-4301-a46a-0297fab04ee5.1.20690323.err.log
8,0K	/path/to/testToil/tmp/toil_2d089094-e812-4301-a46a-0297fab04ee5.1.20690323.out.log

Please find attached debug logs for both a big file and a small file.

[smallfile.txt](https://github.com/user-attachments/files/16909738/smallfile.txt)
[bigfile.txt](https://github.com/user-attachments/files/16909740/bigfile.txt)

**Comment by stxue1** [comment]
Thanks for the debug logs. I think I see where it's going wrong now. The S3 download is happening twice on your machine when it should only be happening once. The second download where it says:
```
Executing task IOWriteTask(transfer_id=0, {'offset': 0}) with kwargs {'fileobj': <_io.BufferedWriter name='/path/to/testToil/jobstore1/files/no-job/file-61aa016b1a484543a7bac83688efc3a9/stream'>, 'offset': 0}
```
Is the same streaming download to the jobstore that I'm seeing. But the first download:
```
[2024-09-06T14:30:15+0000] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] Executing task ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'my-bucket', 'key': 'small_file.txt', 'extra_args': {}}) with kwargs {'client': <botocore.client.S3 object at 0x1497d0eb50d0>, 'bucket': 'my-bucket', 'key': 'small_file.txt', 'fileobj': <tempfile._TemporaryFileWrapper object at 0x1497d1dfad30>, 'extra_args': {}, 'callbacks': [], 'max_attempts': 5, 'download_output_manager': <s3transfer.download.DownloadSeekableOutputManager object at 0x1497d1dfaa90>, 'io_chunksize': 262144, 'bandwidth_limiter': None}
```
seems to only happen on your machine. I believe Toil is hitting this branch here:
https://github.com/DataBiosphere/toil/blob/8a8fed427cb46ab5cc78db11ad34d6d34d9e1817/src/toil/cwl/cwltoil.py#L1346-L1383

Which is quite odd; this function is invoked indirectly through cwltool's internals. In the latest version, before the workflow is executed, this is only invoked 3 times to set up certain directories, and not to download an AWS bucket.

What version of cwltool is installed on your machine? It may be possible an older version of cwltool is attempting to download the inputs themselves.

**Comment by Anael09** [comment]
Hi @stxue1,
cwltool --version was giving me **3.1.20230425144158** so I tried with **3.1.20240112164112** and indeed it seems that it solves the issue!
Thank you very much for your support and analysis!

**Comment by mr-c** [comment]
Thanks for the update @Anael09 ; I see from the logs that you are running toil version `5.11.0-9a04dabb36d6ab13ed1ac7c711dbdc8c71724dc9` from June, 2023; the latest toil version is 7.0.0 from May, 2024. I hope that the new version also works for you!
