### ISSUE TITLE
Single machine batch system should schedule based on fit rather than age of jobs

### ISSUE THREAD

**Issue by dgaston** [DataBiosphere/toil#616]
I have been running toil on just a single machine (until my personal cluster finally arrives). My current pipeline script can be found here: https://github.com/dgaston/ddbio-ngsflow/blob/master/workflow-somatic_amplicon.py

I am currently executing this script with --maxCores 8 and --maxMemory 12884901888 (12G). As you can see I create per sample jobs when constructing the job tree. The first job for every sample is BWA. If I say that each BWA job only needs say 4 cores and 6 GB of RAM it will happily start two BWA jobs in parallel as I expect. If I say that each BWA job needs more cores or RAM, enough that only one BWA job can run on the machine at once, as expected it only executes the one BWA job. The child of each BWA job is part of the Picard/GATK workflow and each of those jobs have a low number of cores and ram assigned (2 cores, 2 GB) so it should be able to start executing the next BWA job while the GATK jobs are running; however it doesn't. It will go through each job in that sample's workflow before going to the next sample.

I suspect this is because of how I construct my job tree, although it isn't as I expected. Is there a way to view the job tree somehow so I can see if the job tree has the form I expect? And secondly if the tree does has the form I expect, why does it appear as if the workflow is going through all of the jobs for a sample before going to the next? Each BWA job should be a child of the root job.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-322)
┆Issue Number: TOIL-322

**Comment by hannes-ucsc** [comment]
The single machine batch system enforces a stronger ordering than necessary. It has strict FIFO semantics because it only uses a single job queue. IOW, it will only look at the head of the queue and wait until it can ran that job with the available resources, even if there are jobs later in the queue that could run with the currently available resources. This is dumb and needs to be changed. I propose we use this ticket to track that effort.

In the meantime, I suggest that you use the Mesos batch system, even on a single machine. You'd have to install Mesos and start its master and slave processes before running your pipeline script. IIRC, you were targeting Mesos anyways, am I right?

Related to #563

**Comment by dgaston** [comment]
Yes that's correct. I just need to reinstall mesos on my local machine. I had it running previously for some testing I was doing. Thanks for the suggestion, it's a good idea.

**Comment by DailyDreaming** [comment]
Stale, closing.  Reopen if still an issue.

**Comment by adamnovak** [comment]
We redid the single machine scheduling; I think it now loops around over all the queued jobs looking for any that can run.
