### ISSUE TITLE
Implement importAsSymlink method that avoids copying a key from existing buckets

### ISSUE THREAD

**Issue by nsjake** [DataBiosphere/toil#819]
Instead a new bucket is created specifically for symlinks e.g. `{jobstore name}--links` each key in this bucket contains only the bucket, region, and key information to other buckets. This would only work for unencrypted keys. This could however also be applied to other cloud services, there could be (along with credentials) relevant info for reading from and writing to say an azure blob or google bucket.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-339)
┆Issue Number: TOIL-339

**Comment by JakeNarkizian** [comment]
Possible issues to consider:

- sym linked points to a file that does not exist 
- sym link points to encrypted file
- sym link points to read only file
- sym linked file is deleted after import
- sym link points to unencrypted file when jobStore is encrypted
- some write operation on a sym linked file is overwritten due to some concurrent write outside of toil
- ditto for read operations reading outdated versions of files

**Comment by DailyDreaming** [comment]
Stale.  Please reopen if still an issue.
